import './states.mjs';
import './user-design.mjs';
import './user-fields.mjs';
import './user-core.mjs';
import './user-live.mjs';
import './guild-design.mjs';
import './admin-core.mjs';
import './admin-config.mjs';
import './admin-finance.mjs';
import './calculations.mjs';
import './user-assets.mjs';
import './field-design.mjs';
import './query-design.mjs';
import './user-completion.mjs';
import './source-completion.mjs';
import './guild-completion.mjs';
import './admin-completion.mjs';
import './additional-results.mjs';
import './user-result-completion.mjs';
import './remaining-guild-results.mjs';
import './cross-end-projection.mjs';
import './review-adjustments.mjs';
import {saveDesign,sourceErrors} from './design.mjs';
if(sourceErrors.length) throw new Error(JSON.stringify(sourceErrors,null,2));
else await saveDesign();
