import {test,ref,page,designs} from './design-cases.mjs';
for(const [state,result]of [['正常公会长','进入选择公会页'],['账号错误','显示“账号或密码错误”'],['密码错误','显示“账号或密码错误”'],['公会长已停用','不建立公会端登录会话'],['运营账号','不建立公会端登录会话']])test('guild-login.html',state==='运营账号'?'运营账号不能':state==='公会长已停用'?'公会长账号被停用':'登录校验',`公会登录${state}`,[`测试登录凭证A状态为${state}`],['打开公会登录','输入测试账号A及对应密码','点击“登录”'],result,{point:'公会登录分流',role:state==='运营账号'?'运营账号':'公会长',dimension:state==='正常公会长'?'正常主流程':'权限差异'});
for(const field of ['公会账号','密码'])test('guild-login.html',field+'：',`公会登录${field}留空`,['另一个登录字段已有可用凭证'],['打开公会登录',`清空“${field}”`,'点击“登录”'],'不建立公会端登录会话',{point:'登录必填',dimension:'输入边界'});
for(const state of ['可管理未解散','不可管理','已解散'])test('guild-switch.html','仅展示',`选择公会范围${state}`,[`公会长A已登录，公会G1状态为${state}`],['打开选择公会'],state==='可管理未解散'?'列表展示G1':'列表不提供G1可选项',{point:'可管理公会范围',dimension:'权限差异'});
test('guild-switch.html','选择公会 ->','公会切换刷新数据',['公会长A可管理G1和G2，当前G1收益100金币，G2收益200金币'],['打开选择公会','点击G2'],'首页展示G2的200金币收益',{point:'切换公会数据隔离'});
const join='guild-join-review-detail.html';
for(const action of ['通过','驳回'])for(const outcome of action==='通过'?['提交平台终审','申请人仍为普通用户']:['本次申请结束','申请人未加入公会'])test(join,action==='通过'?'公会通过仅提交':'平台驳回',`公会初审${action}后${outcome}`,['A为普通用户，向G1提交唯一待公会审核申请J1，认证资料完整'],['打开J1入会申请详情',`点击“${action}”`,'确认审核'],outcome,{point:'公会初审分流',flow:'FLOW-GUILD-JOIN',sources:[ref(join,'驳回 ->')]});
test(join,'二次确认','初审通过取消确认',['J1为待公会审核'],['打开J1申请详情','点击“通过”','点击“取消”'],'J1仍为待公会审核',{point:'初审取消',dimension:'中断/取消',flow:'FLOW-GUILD-JOIN'});
for(const state of ['公会已通过','公会已驳回','平台已通过','平台已驳回'])test(join,'已处理申请只读',`${state}申请不可重复初审`,[`J1状态为${state}`],['打开J1入会申请详情'],'申请仅可查看，不可重复公会审核',{point:'已处理申请只读',dimension:'重复操作'});
for(const reason of ['', '测'.repeat(200),'测'.repeat(201)])test(join,'驳回理由',`入会驳回理由${reason.length}字`,['J1待公会审核'],['打开J1入会申请详情','点击“驳回”',`输入驳回理由为${reason.length}个“测”`,'确认驳回'],reason.length<=200?'J1更新为公会驳回':'不保存超过200字的驳回理由',{point:'初审理由边界',dimension:'输入边界'});
for(const [tab,states]of [['审核中','待公会审核、平台审核中'],['已通过','平台终审通过'],['已驳回','公会驳回、平台驳回']])test('guild-join-review.html','状态：',`入会列表${tab}归类`,['同一公会存在各审核状态的独立测试申请'],['打开入会审批',`切换“${tab}”`],`列表仅展示${states}申请`,{point:'入会状态筛选',flow:'FLOW-GUILD-JOIN'});
const leave='guild-leave-review-detail.html';
for(const outcome of ['当前直播结束','公会关系解除','主播身份解除'])test(leave,'通过 ->',`退会通过后${outcome}`,['主播A属于G1，S1正在直播，退会申请L1待公会审核'],['打开L1退会申请详情','点击“通过”','确认通过'],outcome,{point:'公会退会批准',flow:'FLOW-GUILD-LEAVE'});
for(const outcome of ['公会关系保留','主播身份保留','主播可重新提交退会申请'])test(leave,'驳回 ->',`退会驳回后${outcome}`,['A为G1主播，退会申请L1待审核'],['打开L1退会申请详情','点击“驳回”','确认驳回'],outcome,{point:'退会驳回',flow:'FLOW-GUILD-LEAVE'});
test(leave,'二次确认','取消退会通过',['L1待审核，A仍属于G1且正在直播'],['打开L1退会申请详情','点击“通过”','点击“取消”'],'L1保留待审核状态',{point:'退会审核取消',dimension:'中断/取消'});
for(const state of ['已通过','已驳回'])test(leave,'已处理记录只读',`退会${state}记录只读`,[`L1${state}`],['打开L1退会申请详情'],'不提供再次审核操作',{point:'退会防重复审核',dimension:'重复操作'});
for(const result of ['显示处理时间','显示处理结果','驳回节点显示理由“资料需补充”'])test(leave,'处理信息',`退会审核详情${result}`,['L1已驳回，处理时间2026-09-14 10:00，理由“资料需补充”'],['打开L1退会申请详情'],result,{point:'退会处理快照'});
const detail='guild-host-detail.html';
for(const [locked,guildOn,platformOn,expected]of [[false,true,true,'公会开关显示开启'],[false,false,true,'公会开关显示关闭'],[true,false,true,'公会开关只读并跟随平台开启'],[true,true,false,'公会开关只读并跟随平台关闭']])test(detail,'平台锁定公会管理权限',`平台${platformOn?'开':'关'}且${locked?'锁定':'未锁定'}、公会原${guildOn?'开':'关'}`,[`A为G1主播；平台权限${platformOn?'开启':'关闭'}，管理${locked?'锁定':'未锁定'}，公会原设置${guildOn?'开启':'关闭'}`],['打开A的主播详情'],expected,{point:'直播权限优先级',dimension:'权限差异',flow:'FLOW-LIVE-PERMISSION',sources:[ref(detail,'开播需同时满足')]});
test(detail,'解除锁定后恢复','平台解锁恢复公会原设置',['A的公会原权限关闭；平台锁定开启使公会展示开启，现平台已解除锁定'],['打开A的主播详情'],'公会权限恢复显示关闭',{point:'公会权限解锁恢复',flow:'FLOW-LIVE-PERMISSION'});
for(const expected of ['A的当前直播S1结束','A不能再次开播'])test(detail,'关闭正在直播',`公会关闭开播权限后${expected}`,['A在G1，平台开启且未锁定公会管理，A正在S1直播'],['打开A的主播详情','关闭直播权限开关','确认关闭'],expected,{point:'公会关闭开播权限',flow:'FLOW-LIVE-PERMISSION'});
test(detail,'存在未结清收益','主播有未结清收益时移出禁用',['A属于G1且存在1笔未结清收益'],['打开A的主播详情'],'移出公会按钮不可用',{point:'移出公会财务限制',dimension:'权限差异',flow:'FLOW-GUILD-LEAVE'});
test(detail,'确认移出后','移出主播解除公会关系',['A属于G1，没有未结清收益，S1正在直播'],['打开A的主播详情','点击“移出公会”','确认移出'],'A与G1关系解除',{point:'公会主动移出',flow:'FLOW-GUILD-LEAVE'});
for(const [kind,target]of [['业绩','主播数据'],['直播记录','直播记录'],['违规记录','违规记录'],['主播分成','主播分成记录']])test(detail,kind==='业绩'?'点击业绩':'快捷入口',`主播详情进入${target}`,['当前查看主播A（ID620100）'],['打开A的主播详情',`点击“${kind}”`],`进入A的${target}页面`,{point:'主播关联页面'});
test('guild-member-list.html','历史退会主播','公会保留退会主播',['A已从G1退出，B仍在G1，C从未加入G1'],['打开公会成员列表'],'展示带“退会”标记的A',{point:'历史公会成员'});
test('guild-member-list.html','共同生效','成员状态与搜索组合',['A名称测试A且在会，B名称测试B且已退会'],['打开公会成员列表','切换“已退会”','输入搜索词“测试”'],'仅显示测试B',{point:'成员筛选交集'});
const compose='guild-message-compose.html';
for(const mode of ['全体主播','指定主播'])test(compose,'二次确认接收范围',`公会消息发送给${mode}`,['G1有在会主播A、B，已退会C；内容“今日活动”',mode==='指定主播'?'已选中A':'发送范围为全部在会主播'],['打开发送公会消息',`选择“${mode}”`,'输入消息“今日活动”','点击“发送”','确认接收范围'],`生成面向${mode==='全体主播'?'A、B':'A'}的消息记录`,{point:'公会消息发送范围',flow:'FLOW-GUILD-MESSAGE'});
test(compose,'指定主播时必选','指定主播模式未选人',['消息内容已填写“今日活动”'],['打开发送公会消息','选择“指定主播”','点击“发送”'],'不生成未指定接收人的消息',{point:'发送对象必选',dimension:'输入边界'});
for(const n of [0,1,499,500,501])test(compose,'最多 500',`公会消息正文${n}字`,['发送对象为当前公会全体主播，无图片'],['打开发送公会消息',`输入${n}个“测”作为消息正文`,'点击“发送”','确认接收范围'],n>=1&&n<=500?`生成正文长度${n}字的消息记录`:'不保存空正文或超过500字的消息',{point:'公会消息长度',dimension:'输入边界'});
for(const type of ['JPG','PNG','WebP'])test(compose,'支持 JPG',`公会消息附加${type}图片`,['正文“今日活动”，发送对象全体主播，一张可读取的'+type+'图片A'],['打开发送公会消息',`上传${type}图片A`,'点击“发送”','确认接收范围'],'消息记录包含上传图片A',{point:'消息图片格式'});
test(compose,'发送后不支持编辑或撤回','已发送公会消息不可修改',['M1已发送给主播A、B'],['打开M1消息详情'],'不提供编辑或撤回操作',{point:'消息发送不可变更'});
test('guild-message-detail.html','接收人后续退会','接收人退会不改消息快照',['M1发送给A和B，发送时实际人数2；A后来退会'],['打开M1消息详情'],'实际接收人数仍显示2',{point:'接收范围历史快照',flow:'FLOW-GUILD-MESSAGE'});
for(const [key,object]of [['guild-host-select.html','主播'],['guild-operation-account-select.html','运营账号'],['guild-violation-host-select.html','主播']]){
 for(const term of ['测试A','620100','不存在XYZ'])test(key,'模糊匹配',`${page(key).name}按${term}搜索`,[`可选${object}测试A的ID为620100，另有测试B`],[`打开${page(key).entry}`,`输入搜索词“${term}”`],term==='不存在XYZ'?'列表显示无匹配结果':`仅显示${object}测试A`,{point:'选择器模糊搜索'});
 if(key!=='guild-host-select.html')for(const action of ['全选','取消全选'])test(key,key==='guild-violation-host-select.html'?'全选全部主播':'全选作用于全部',`${page(key).name}${action}`,['本公会有3个可选对象，其中搜索只显示1个'],[`打开${page(key).entry}`,`点击“${action}”`],action==='全选'?'选中本公会全部3个对象':'全部对象取消选中',{point:'全选作用范围'});
}
test('guild-host-select.html','仅可选择 1','公会消息接收人单选',['G1有主播A和B'],['打开选择主播','选择A','选择B','点击“完成”'],'消息发送页仅回填主播B',{point:'指定主播单选'});
test('guild-operation-account-select.html','保留日期条件','运营账号选择返回保留日期',['送礼记录日期范围2026-09-01至2026-09-14，账号A和B可选'],['打开选择运营账号','选择A','选择B','点击“完成”'],'送礼记录保留原日期条件',{point:'选择器返回条件'});
test('guild-violation-host-select.html','保留其他筛选条件','主播选择返回保留违规范围',['违规记录已选账号违规、2026-09-01至09-14'],['打开选择主播','选择A','点击“完成”'],'违规记录保留账号违规及原日期范围',{point:'多条件返回保持'});
for(const lang of ['简体中文','英文','印尼语','马来语'])test('guild-settings.html','语言：',`公会端切换${lang}`,['当前账号A可用'],['打开公会设置',`选择语言“${lang}”`],`公会端界面切换为${lang}`,{point:'公会端语言'});
test('guild-settings.html','不修改公会或主播资料','切换语言不改业务资料',['G1名称为公会A，主播B名称为测试B'],['打开公会设置','选择语言“英文”'],'公会和主播原资料保持不变',{point:'语言数据隔离'});
test('guild-settings.html','退出登录','公会退出登录确认',['公会长A已登录G1'],['打开公会设置','点击“退出登录”','确认退出'],'返回公会登录页',{point:'公会会话退出'});
const password='guild-password.html';
for(const [old,next,confirm,expected]of [['WrongPass','NewPass12','NewPass12','显示“当前密码错误”'],['OldPass12','OldPass12','OldPass12','显示“新密码不能和旧密码一样”'],['OldPass12','NewPass12','OtherPass12','不更新密码'],['OldPass12','1234567','1234567','不保存少于8位的新密码'],['OldPass12','NewPass12','NewPass12','更新密码为NewPass12']])test(password,'新密码',`修改公会密码：${expected}`,['当前密码OldPass12'],['打开修改密码',`输入当前密码“${old}”`,`输入新密码“${next}”`,`输入确认密码“${confirm}”`,'点击“保存”'],expected,{point:'公会密码校验',sources:[ref(password,'当前密码错误'),ref(password,'确认新密码')]});
test(password,'请求失败','修改公会密码请求失败',['当前密码OldPass12；本次保存请求返回失败'],['打开修改密码','输入当前密码“OldPass12”','输入新密码与确认密码“NewPass12”','点击“保存”'],'显示“保存失败”',{point:'密码修改失败',dimension:'异常/失败'});
export default designs;
