import {test,ref,page,designs} from './design-cases.mjs';
const review='admin-host-review-detail.html';
for(const verdict of ['通过','驳回'])test(review,'仅待审核可处理',`平台终审${verdict}`,['申请J1已公会初审通过、待平台终审，申请人A仍为普通用户'],['打开J1审核详情',`选择“${verdict}”`,...(verdict==='驳回'?['输入驳回原因“证件不清晰”']:['选择平台直播权限开启和允许公会管理']),'点击“确认”'],`J1审核结果固化为${verdict}`,{point:'平台终审结果',flow:'FLOW-GUILD-JOIN'});
test(review,'通过后加入申请公会','平台通过生成主播身份',['A申请加入G1，J1已公会初审通过，认证材料完整'],['打开J1审核详情','选择“通过”','点击“确认”','打开主播列表','查询用户A'],'A以主播身份归属G1',{point:'终审身份转换',flow:'FLOW-GUILD-JOIN'});
test(review,'驳回原因：','平台驳回原因必填',['J1待平台终审'],['打开J1审核详情','选择“驳回”','清空驳回原因','点击“确认”'],'不提交无原因的驳回结论',{point:'终审驳回原因',dimension:'输入边界'});
for(const state of ['已通过','已驳回'])test(review,'禁止重复提交',`平台终审${state}不可再处理`,[`J1${state}`],['打开J1审核详情'],'不提供再次提交审核结果的操作',{point:'平台终审终态',dimension:'重复操作'});
test(review,'按申请保留快照','审核材料不跟随后续资料变化',['J1提交时实名为测试A，照片为材料A；个人资料后来变为测试B'],['打开J1审核详情','查看认证材料'],'J1继续展示提交时的测试A与材料A',{point:'审核材料快照'});
for(const [lo,hi,good]of [[0,0,true],[0,1,true],[1,0,false],[-1,2,false],[1.5,2,false]])test('admin-user-list.html','筛选上下限',`用户等级区间${lo}至${hi}`,['系统存在当前等级0、1、2的测试用户'],['打开用户列表',`输入财富等级下限${lo}与上限${hi}`,'点击“查询”'],good?`结果仅包含等级在${lo}至${hi}的用户`:'不执行非法等级区间查询',{point:'等级筛选边界',dimension:'输入边界'});
for(const action of ['封禁','解封'])test('admin-user-list.html','填写原因并确认',`账号${action}原因留痕`,[`A当前账号状态允许${action}`],['打开用户列表','查询A',`点击“${action}”`,'输入原因“测试处置”','点击“确认”'],`记录A的${action}原因、操作人和时间`,{point:'账号状态变更留痕',flow:'FLOW-ACCOUNT-BAN'});
test('admin-user-detail.html','解封只恢复登录','账号解封不恢复直播权限',['主播A处于账号封禁且平台直播权限关闭'],['打开A的用户详情','点击“解封”','输入原因“测试解封”','点击“确认”','打开A的主播详情'],'A的平台直播权限仍关闭',{point:'账号权限相互独立',flow:'FLOW-ACCOUNT-BAN'});
for(const op of ['警告','关播'])test('admin-live-detail.html','警告不改状态',`平台直播详情${op}`,['场次S1正在直播'],['打开S1直播详情',`点击“${op}”`,'输入原因“测试处置”','点击“确认”'],op==='警告'?'S1状态保持直播中':'S1状态更新为已结束',{point:'直播即时处置',flow:'FLOW-LIVE-DISPOSITION'});
test('admin-live-detail.html','已结束只读','已结束场次不可即时处置',['S1已结束，主播另开S2'],['打开S1直播详情'],'不提供对S1的即时警告或关播操作',{point:'历史场次只读',dimension:'权限差异'});
for(const action of ['忽略','转人工复审'])test('admin-content-audit.html','忽略表示误报',`机审告警${action}`,['机审告警A待处理，关联S1直播中'],['打开内容审核','打开告警A',`选择“${action}”`,'输入原因“测试复核”','点击“提交”'],action==='忽略'?'A更新为已忽略':'A更新为人工复审中',{point:'告警人工分流',flow:'FLOW-CONTENT-AUDIT'});
test('admin-content-audit.html','不直接处罚','机审命中不直接处罚',['机审生成高风险告警A，尚未人工处理，S1正在直播'],['打开内容审核','查看告警A'],'告警A不直接产生处罚结果',{point:'机审与处置分离'});
test('admin-content-audit-detail.html','处置原因：','机审复审原因必填',['告警A待处理'],['打开A审核详情','选择“忽略”','清空原因','点击“提交”'],'不提交缺少原因的复审结果',{point:'内容复审原因',dimension:'输入边界'});
for(const state of ['已忽略','已处置'])test('admin-content-audit-detail.html','为终态',`机审${state}终态`,[`告警A${state}`],['打开A审核详情'],'不可再次提交处理结果',{point:'内容审核终态',dimension:'重复操作'});
const report='admin-report-detail.html';
for(const [kind,actions]of [['账号',['不处置','封禁']],['直播',['不处置','警告','关播','关闭直播权限']]])for(const action of actions)test(report,'处置类型：',`${kind}举报可选${action}`,[`${kind}举报R1待处理且举报成立；直播场次仍在播`],['打开R1举报详情',`选择“${action}”`,...(action!=='不处置'?['输入处置原因“测试举报处置”']:[]),'点击“提交”'],'R1状态更新为已处理',{point:`${kind}举报处置种类`,flow:kind==='账号'?'FLOW-ACCOUNT-REPORT':'FLOW-LIVE-REPORT'});
test(report,'举报不成立只能不处置','举报不成立不得处罚',['举报R1待处理，结论选择不成立'],['打开R1举报详情'],'仅允许不处置结果',{point:'不成立举报边界',dimension:'权限差异'});
for(const action of ['警告','关播','关闭直播权限'])test(report,'处置原因：',`${action}缺少原因拒绝提交`,['直播举报R1成立且当前场次仍在播'],['打开R1举报详情',`选择“${action}”`,'清空处置原因','点击“提交”'],'不提交缺少原因的处罚结果',{point:'举报处罚原因',dimension:'输入边界'});
for(const state of ['已处理','已作废'])test('admin-report-handling.html','只读',`直播举报${state}只读`,[`R1${state}`],['打开R1直播举报详情'],'不提供再次处置操作',{point:'直播举报终态',dimension:'重复操作',flow:'FLOW-LIVE-REPORT'});
test('admin-report-handling.html','工单自动作废','直播结束使待处理举报作废',['S1有待处理举报R1，S1现已结束'],['打开直播举报列表','查询R1'],'R1显示已作废',{point:'直播举报场次结束',flow:'FLOW-LIVE-REPORT'});
test(report,'不补关下一场直播','旧举报不能处置新场',['R1属于已结束S1且未处理，主播已开S2'],['打开R1举报详情'],'不提供对S2补充关播的操作',{point:'举报场次隔离',flow:'FLOW-LIVE-REPORT'});
for(const [action,state]of [['警告','直播中'],['关播','已结束'],['关闭直播权限','已结束']])test(report,'警告继续直播',`直播举报${action}后的场次状态`,['R1举报成立且关联S1仍在播'],['打开R1举报详情',`选择“${action}”`,'输入原因“测试”','点击“提交”','打开S1直播详情'],`S1显示${state}`,{point:'举报处置场次结果',flow:'FLOW-LIVE-REPORT'});
const guild='admin-guild-detail.html';
for(const result of ['公会状态保持启用','该公会主播保持原身份','该公会主播开播权限保持原值'])test(guild,'公会长账号状态与公会状态独立',`停用公会长后${result}`,['G1启用，公会长A启用，主播B在G1且直播权限开启'],['打开G1公会详情','关闭公会长A账号开关','点击第一次“确认”','点击第二次“确认”'],result,{point:'公会长账号独立状态',flow:'FLOW-GUILD-ACCOUNT'});
for(const round of [1,2])test(guild,'连续确认两次',`公会长停用第${round}次取消`,['G1公会长A已启用'],['打开G1公会详情','关闭公会长A账号开关',...(round===2?['点击第一次“确认”']:[]),'点击“取消”'],'公会长A账号保留启用状态',{point:'公会长两次确认',dimension:'中断/取消'});
for(const [unsettled,expected]of [[1,'不能解散G1'],[0,'G1状态更新为已解散']])test('admin-guild-list.html','未结收益为 0',`公会解散未结收益${unsettled}`, [`G1未结收益${unsettled}USD`],['打开公会列表','查询G1','点击“解散”','确认解散'],expected,{point:'公会解散财务门槛',dimension:'输入边界',flow:'FLOW-GUILD-DISSOLVE'});
test('admin-guild-list.html','已解散为终态','已解散公会不可恢复',['G1已解散'],['打开公会列表','查询G1'],'不提供重新启用G1的操作',{point:'公会解散终态',dimension:'权限差异'});
for(const result of ['公会状态更新为停用','所有管理账号不能登录公会端','各管理账号自身启停值保留','旗下主播公会关系解除'])test('admin-guild-list.html','公会停用',`停用公会后${result}`,['G1启用，管理账号A启用、账号B停用，主播C在会'],['打开公会列表','查询G1','点击“停用”','确认停用'],result,{point:'公会停用范围',flow:'FLOW-GUILD-DISABLE',sources:[ref('admin-guild-list.html','旗下主播将退出')]});
const sched='admin-inspection-schedule-create.html';
for(const offset of [-1,0,1])test(sched,'日期：',`巡房日期相对当前${offset}天`,['测试业务日期2026-09-14，人员A可用，时段20:00至21:00'],['打开新建排班',`选择日期2026-09-${14+offset}`,'选择人员A','点击“保存”'],offset<0?'不保存早于当前日期的排班':'创建所选日期排班',{point:'巡房日期下界',dimension:'输入边界'});
for(const [start,end,valid]of [['20:00','19:59',false],['20:00','20:00',false],['20:00','20:01',true]])test(sched,'结束晚于开始',`巡房时段${start}至${end}`,['排班日期为今日，人员A可用'],['打开新建排班',`输入开始${start}、结束${end}`,'选择人员A','点击“保存”'],valid?'创建巡房排班':'不保存结束不晚于开始的排班',{point:'巡房时段边界',dimension:'输入边界'});
for(const n of [0,1])test(sched,'至少 1',`巡房选择${n}名人员`,['日期与时段均有效'],['打开新建排班',n?'选择可用账号A':'清空全部人员选择','点击“保存”'],n?'创建包含人员A的排班':'不保存无人员排班',{point:'巡房人数下界',dimension:'输入边界'});
test(sched,'封禁账号不可加入','巡房排班排除封禁账号',['A已被平台封禁'],['打开新建排班','打开添加人员','搜索A'],'A不可加入巡房人员名单',{point:'巡房账号资格',dimension:'权限差异'});
test(sched,'全选仅作用当前结果','巡房人员全选只作用搜索结果',['可用账号A、B、C，当前搜索仅显示A、B'],['打开添加巡房人员','点击“全选”'],'仅勾选A、B',{point:'巡房人员全选范围'});
for(const action of ['停用','重新启用'])test('admin-inspection-schedule.html','重新启用',`巡房排班${action}`,['排班P1时间仍处于当前有效时段'],['打开巡房排班','选择P1',`点击“${action}”`,'确认变更'],action==='停用'?'P1不再赋予巡房会话资格':'P1恢复生效中状态',{point:'巡房排班启停',flow:'FLOW-PATROL'});
for(const [key,entity]of [['admin-system-account.html','后台账号'],['admin-system-role.html','后台角色']]){
 test(key,'超级管理员',`内置超级管理员${entity}保护`,['当前查看内置超级管理员对象'],[`打开${page(key).entry}`],'不可停用内置超级管理员对象',{point:'内置维护权限保护',role:'超级管理员',dimension:'权限差异'});
 test(key,key.includes('role')?'失去该角色权限':'禁止登录',`停用普通${entity}`,['普通对象A已启用，绑定后台登录账号B'],[`打开${page(key).entry}`,'关闭A启用开关',...(entity==='后台账号'?['输入原因“测试停用”']:[]),'确认停用'],entity==='后台账号'?'A不能登录后台':'B失去A角色授予的菜单权限',{point:'后台账号角色停用',role:'超级管理员',flow:'FLOW-ADMIN-PERMISSION'});
}
const role='admin-system-role-detail.html';
for(const op of ['勾选父级','取消全部子级','全选','全不选'])test(role,'父级',`角色权限树${op}`,['角色R1非内置，父菜单P含子菜单A和B'],['打开R1角色编辑',op==='勾选父级'?'勾选父菜单P':op==='取消全部子级'?'取消勾选P下全部子菜单':`点击“${op}”`],op==='勾选父级'?'子菜单A、B同时被选中':op==='取消全部子级'?'父菜单P同步取消选中':op==='全选'?'全部叶子权限被勾选':'全部叶子权限取消勾选',{point:'权限树联动',role:'超级管理员'});
test(role,'已选择数','角色权限数只计叶子节点',['父菜单P有两个子叶A、B，另有独立叶C'],['打开角色编辑','勾选父菜单P','勾选叶C'],'已选择权限数显示3',{point:'叶子权限计数',role:'超级管理员'});
test(role,'对关联账号立即生效','角色权限保存应用到关联账号',['R1绑定账号A，当前无用户管理菜单权限'],['打开R1角色编辑','勾选用户管理叶子权限','点击“保存”'],'R1关联账号A获得用户管理菜单权限',{point:'角色权限生效',role:'超级管理员',flow:'FLOW-ADMIN-PERMISSION'});
test('admin-system-account-detail.html','两次一致','后台重置密码两次不一致',['普通后台账号A可编辑'],['打开A账号编辑','输入新密码“NewPass123”','输入确认密码“OtherPass123”','点击“保存”'],'不替换A的旧密码',{point:'后台密码一致性',role:'超级管理员',dimension:'输入边界'});
export default designs;
