import {test,P0,P1,P2,ERR,enter,calculation} from './case-design.mjs';
const g=(page,refs,title,point,pre,steps,result,o)=>{
 const prepared=pre.length>0&&steps[0]===enter(page);
 return test(page,refs,'公会长',title,point,[...(prepared?['业务数据已准备且本页已打开；表单和筛选保持下列指定状态']:[]),...pre],prepared?steps.map((s,i)=>i===0?s.replace(/^进入\|/,'查看|'):s):steps,result,o);
};
const login='guild-login.html',choose='guild-switch.html',home='guild-home.html';
g(login,['登录校验通过'],'公会长有效凭证登录','公会登录成功去向',['平台已创建并启用公会长qa-chief，测试密码QaChief!2026'],[enter(login),'填写|公会账号|为qa-chief','填写|密码|为QaChief!2026','点击|登录'],'进入选择公会页',P0);
for(const field of ['公会账号','密码'])g(login,[`${field}：`],`公会登录漏填${field}`,`${field}必填`,['公会长qa-chief已启用，密码QaChief!2026'],[enter(login),'填写|公会账号|为qa-chief','填写|密码|为QaChief!2026',`清空|${field}`,'点击|登录'],'不能提交缺少必填项的登录',P1);
for(const reason of ['账号不存在','密码错误'])g(login,['账号或密码错误'],`${reason}时统一提示`,'公会登录错误提示',['qa-unknown不存在；qa-chief已启用且正确密码QaChief!2026'],[enter(login),`填写|公会账号|为${reason==='账号不存在'?'qa-unknown':'qa-chief'}`,'填写|密码|为Wrong!2026','点击|登录'],'提示“账号或密码错误”',ERR);
g(login,['公会长账号被停用后不可登录'],'停用公会长不能登录','公会长停用登录限制',['平台已经停用该公会长，密码仍为原正确值'],[enter(login),'填写|公会账号|为已停用账号','填写|密码|为原正确密码','点击|登录'],'不能进入选择公会页',{...P1,transition:'ST-chief-disable'});
test(login,['运营账号不能登录公会端'],'运营账号','运营账号不能冒用公会登录','公会登录角色边界',['运营账号qa-ops及其密码有效'],[enter(login),'填写|公会账号|为qa-ops','填写|密码|为该运营账号密码','点击|登录'],'不能进入选择公会页',P1);
g(choose,['仅展示当前账号可管理且未解散'],'选择公会限定管理范围','可管理公会范围',['账号可管理公会A和已解散B，无权管理C'],[enter(choose)],'可选择公会仅包含A',P1);
g(choose,['更新当前公会，返回首页'],'切换到另一可管理公会','切换公会首页数据',['当前为A，账号有权管理B'],[enter(choose),'点击|选择公会B'],'首页显示公会B',P1);
g(choose,['当前选中的公会显示'],'选择公会页标记当前对象','当前管理公会标识',['当前管理公会为A'],[enter(choose)],'公会A显示“当前公会”',P2);
g(home,['正在直播的去重主播数'],'首页统计在播主播人数','公会实时在播人数',['公会A有主播甲、乙在播，丙已下播，其他公会另有主播在播'],[enter(home)],'直播中显示2人',P1);
g(home,['满 3 小时的主播数'],'首页统计有效天达标主播','公会有效天达标人数',['当前公会甲当天有效直播180分钟、乙179分钟、丙360分钟'],[enter(home)],'达成有效天显示2人',P1);
g(home,['当前公会当日主播收益金币汇总'],'公会首页收益不等于最终分成','公会当日金币收益',['当天在会主播甲收益1000金币、乙500金币；财务上传分成为10美元'],[enter(home)],'当日收益 = 1500',{...P1,calc:calculation('甲收益+乙收益',{甲收益:1000,乙收益:500},{运算:'+',参数:[{变量:'甲收益'},{变量:'乙收益'}]},1500)});
for(const [button,dest]of [['公会名称','选择公会页'],['通知','通知消息页'],['账号设置','账号设置页'],['今日概况','当日经营详情页']])g(home,[button==='公会名称'?'点击进入选择公会':button],`首页进入${button}`,`公会首页${button}入口`,[],[enter(home),`点击|${button}`],`进入${dest}`,P2);
for(const type of ['入会申请','平台终审结果','退会申请','直播权限','公会状态','运营账号管理权限','主播分成','公会分成'])g('guild-notifications.html',[type],`公会通知展示${type}事件`,`公会${type}通知`,[`环境准备：当前管理公会已产生一条${type}通知`],[enter('guild-notifications.html')],`列表显示该${type}通知`,P2);
g('guild-notification-detail.html',['进入详情 -> 标记为已读'],'进入公会通知详情标记已读','公会通知已读更新',['通知N当前未读'],[enter('guild-notifications.html'),'点击|通知N','返回|通知列表'],'N不再显示未读标记',P2);
for(const allowed of [true,false])g('guild-notification-detail.html',['有关联记录且有权限时显示'],`${allowed?'有':'无'}权限查看通知关联业务`,'公会通知关联入口权限',[`当前通知关联入会申请单，账号${allowed?'有':'无'}访问该记录权限`],[enter('guild-notification-detail.html')],allowed?'显示关联业务入口':'不显示关联业务入口',P1);
for(const key of ['guild-join-review.html','guild-leave-review.html']){
  const noun=key.includes('join')?'入会':'退会';
  g(key,['默认审核中'],`${noun}申请默认待处理列表`,`${noun}默认状态筛选`,[],[enter(key)],'选中审核中Tab',P2);
  for(const state of ['审核中','已通过','已驳回'])g(key,['筛选对应状态'],`${noun}列表筛选${state}`,`${noun}${state}列表范围`,[`当前公会有${state}及其他状态申请`],[enter(key),`切换|${state}`],`只显示属于${state}分类的申请`,P1);
  g(key,['点击申请卡片'],`${noun}列表进入申请详情`,`${noun}详情入口`,['存在当前公会申请单A'],[enter(key),'点击|申请单A'],`进入${noun}申请详情页`,P2);
}
const join='guild-join-review-detail.html',leave='guild-leave-review-detail.html';
g(join,['通过 -> 二次确认'],'通过入会前确认','公会入会通过确认',['当前申请待公会审核'],[enter(join),'点击|通过'],'显示通过申请二次确认弹窗',P1);
g(join,['提交平台终审'],'公会通过后提交平台终审','公会初审通过去向',['申请A待公会审核且资料完整'],[enter(join),'点击|通过','点击|确认'],'申请A进入平台审核中',{...P0,transition:'ST-join-guild-pass'});
for(const [key,noun,transition]of [[join,'入会','ST-join-guild-reject'],[leave,'退会','ST-leave-reject']]){
  g(key,['未填显示「未填写」'],`${noun}驳回不填写理由`,`${noun}空驳回理由回显`,[`当前${noun}申请待公会处理`],[enter(key),'点击|驳回','清空|驳回理由','点击|确认'],'对应驳回理由显示“未填写”',{...P1,transition});
  g(key,['最多 200'],`${noun}驳回理由200字符边界`,`${noun}驳回理由长度`,[`当前${noun}申请待公会处理`],[enter(key),'点击|驳回','填写|驳回理由|为200个A','输入|驳回理由|末尾追加B'],'驳回理由不接受超过200字符',P1);
  g(key,['只读'],`已处理${noun}申请不能重复审核`,`${noun}终态只读`,[`当前${noun}申请已驳回`],[enter(key)],'审核结果只读',P1);
}
for(const field of ['本人照片','证件正面','证件反面'])g(join,['查看大图','证件图片'],`查看申请${field}`,`申请${field}大图`,[`申请包含${field}测试图片A`],[enter(join),`点击|${field}`],'打开所选材料大图',P2);
g(join,['旧单结果不继承'],'平台驳回后新单重新公会审核','重新申请公会审核资格',['旧申请公会通过、平台驳回，用户已提交新申请B'],[enter(join)],'新申请B的公会审核状态为待审核',P1);
g(join,['成为主播后可进入主播详情'],'平台通过后查看主播主页','审核通过主播详情入口',['该申请已通过平台终审'],[enter(join),'点击|查看主页'],'进入该主播详情',{...P1,transition:'ST-join-platform-pass'});
g(leave,['通过需二次确认'],'通过退会前二次确认','退会审核确认',['申请待公会审核','环境准备：测试版本需实现当前批注明确要求的退会二次确认，静态原型尚未接入'],[enter(leave),'点击|通过'],'显示通过退会二次确认弹窗',P1);
g(leave,['通过 -> 立即结束当前直播'],'确认通过退会移除在会关系','退会通过后的公会关系',['申请主播在会且退会待审核'],[enter(leave),'点击|通过','点击|确认',enter('guild-member-list.html'),'切换|已退会'],'该主播显示在已退会列表',{...P0,observe:'guild-member-list.html',extra:[['guild-member-list.html','当前或历史公会关系']],transition:'ST-leave-pass'});
g(leave,['驳回 -> 保留主播身份和公会关系'],'驳回退会保留在会成员','退会驳回后的公会关系',['申请主播在会且退会待审核'],[enter(leave),'点击|驳回','点击|确认',enter('guild-member-list.html'),'切换|在会'],'该主播仍在在会列表',{...P1,observe:'guild-member-list.html',extra:[['guild-member-list.html','当前或历史公会关系']]});
const list='guild-member-list.html',detail='guild-host-detail.html';
g(list,['仅展示当前公会'],'主播列表隔离其他公会','公会主播管理范围',['当前公会A有主播甲，公会B有主播乙'],[enter(list)],'列表不包含乙',P1);
g(list,['状态 Tab 和名称或 ID 搜索共同生效'],'已退会搜索与状态取交集','公会主播组合筛选',['甲已退会，乙在会，两人名称都含QA'],[enter(list),'切换|已退会','输入|搜索框|内容为QA'],'列表只显示甲',P1);
g(detail,['已退会显示【退会】，不显示管理入口'],'历史退会主播不提供管理操作','退会主播管理入口',['该主播已退出当前公会'],[enter(detail)],'不显示主播管理操作入口',P1);
g(detail,['当前关注该主播的人数'],'主播主页粉丝数取当前人数','公会主播当前粉丝数',['主播现有关注者10人，本月新增20人，本月取关15人'],[enter(detail)],'粉丝数显示10人',P1);
g(detail,['平台锁定公会管理权限时'],'平台锁定后公会不可改权限','公会开播权限锁定',['平台开播权限开启且锁定，公会原设置为关闭'],[enter(detail)],'公会直播权限开关只读',{...P1,transition:'ST-platform-live-lock'});
g(detail,['实际开播权限跟随平台开启'],'平台开启锁定时显示平台权限','平台锁定期间权限取值',['平台开播权限开启且锁定，公会锁定前关闭'],[enter(detail)],'实际开播权限显示开启',P1);
g(detail,['解除锁定后恢复锁定前设置'],'解锁后恢复公会原设置','公会权限解锁恢复',['公会原设置关闭，平台开启锁定后又解除锁定'],[enter(detail)],'公会直播权限恢复关闭',{...P1,transition:'ST-platform-live-unlock'});
g(detail,['关闭正在直播主播的权限'],'公会关闭主播权限前确认','公会关闭权限确认',['主播当前在播，平台允许公会管理'],[enter(detail),'禁用|直播权限'],'显示关闭直播权限二次确认弹窗',P1);
g(detail,['禁止再次开播'],'公会关闭主播开播权限','公会开播权限关闭',['平台未锁定，主播当前公会权限开启'],[enter(detail),'禁用|直播权限','点击|确认'],'直播权限显示关闭',{...P1,transition:'ST-guild-live-toggle'});
g(detail,['存在未结清收益时移出公会按钮置灰'],'未结清收益不能移出主播','主播移出结清门槛',['主播存在未结清收益','环境准备：测试版本需实现批注中的收益结清判断，原型尚未接入'],[enter(detail)],'移出公会按钮不可用',P1);
g(detail,['确认移出后'],'已结清收益主播确认移出','公会移出主播',['主播收益已结清且目前在会'],[enter(detail),'点击|移出公会','点击|确认'],'公会关系显示已退会',{...P1,transition:'ST-remove-host'});
const compose='guild-message-compose.html';
for(const length of [0,500,501])g(compose,['文字内容 / 字数'],`运营消息正文长度${length}`,'运营消息正文字数',['发送对象为当前公会主播甲'],[enter(compose),length?`填写|文字内容|为${length}个A`:'清空|文字内容','点击|发送'],length===500?'显示接收范围二次确认':length===0?'不能发送空正文':'正文不接受超过500字符',P1);
for(const format of ['JPG','PNG','WebP'])g(compose,['支持 JPG、PNG、WebP'],`运营消息上传${format}图片`,'运营消息图片格式',['正文和发送对象已填写',`本地有可读取qa.${format.toLowerCase()}图片`],[enter(compose),`上传|图片|选择qa.${format.toLowerCase()}`],'显示所选图片预览',P2);
g(compose,['最多 1 张'],'运营消息最多附带1张图','运营消息图片数量',['已有一张附图A'],[enter(compose),'上传|图片|选择第二张B'],'消息附图数量不超过1张',P1);
g(compose,['生成记录并返回列表'],'确认发送当前公会消息','公会消息发送成功',['正文为QA通知，接收范围为全体当前主播'],[enter(compose),'点击|发送','点击|确认'],'返回运营消息列表',P0);
g('guild-host-select.html',['仅可选 1 人'],'指定消息只能选择1名主播','消息接收主播单选',['当前公会有甲乙两名主播'],[enter('guild-host-select.html'),'选择|主播甲','选择|主播乙'],'仅主播乙保持选中',P1);
g('guild-host-select.html',['未选择时提示选择主播'],'未选接收主播不能完成','指定接收人必选',[],[enter('guild-host-select.html'),'点击|完成'],'提示选择主播',P1);
g('guild-message-detail.html',['接收人后续退会不改变历史记录'],'接收主播退会后保留发送快照','运营消息接收人快照',['消息N发送时接收人甲仍在会，甲随后退会'],[enter('guild-message-detail.html')],'消息N接收人仍显示甲',P1);
g('guild-message-detail.html',['详情只读'],'已发送运营消息不可编辑撤回','已发送消息只读',['消息N已发送'],[enter('guild-message-detail.html')],'不显示编辑或撤回入口',P1);
const profile='guild-profile.html',settings='guild-settings.html',password='guild-password.html';
g(profile,['永久只读'],'公会资料不可编辑ID','公会ID只读',[],[enter(profile),'点击|公会ID'],'公会ID不可编辑',P1);
for(const [field,max]of [['公会名称',40],['公会简介',200]])g(profile,[`${field}：`],`${field}最大长度`,`${field}输入上限`,[],[enter(profile),`填写|${field}|为${max}个A`,`输入|${field}|末尾追加B`],`${field}不接受超过${max}字符`,P1);
g(profile,['公会名称：必填'],'公会名称不能为空','公会名称必填',[],[enter(profile),'清空|公会名称','点击|保存'],'不能保存空公会名称',P1);
g(profile,['更新当前公会资料'],'公会资料保存新名称','公会名称保存',['当前公会名称为QA旧名'],[enter(profile),'填写|公会名称|为QA新名','点击|保存'],'公会名称显示QA新名',P2);
for(const lang of ['中文','English','Bahasa Indonesia','Bahasa Melayu'])g(settings,['语言：'],`公会App选择${lang}`,'公会App语言选择',[],[enter(settings),'点击|语言',`选择|${lang}`],`当前语言显示${lang}`,P2);
g(settings,['退出登录 -> 二次确认'],'公会长退出登录前确认','公会退出登录确认',[],[enter(settings),'点击|退出登录'],'显示退出登录二次确认弹窗',P2);
g(settings,['清除会话并返回登录页'],'确认退出公会App','公会退出登录去向',[],[enter(settings),'点击|退出登录','点击|确认'],'返回公会登录页',P1);
for(const [old,pwd,confirm,expected]of [['BadOld!2026','QaNew!2026','QaNew!2026','提示“当前密码错误”'],['QaOld!2026','QaOld!2026','QaOld!2026','提示“新密码不能和旧密码一样”'],['QaOld!2026','QaNew!2026','QaNew!2026','返回账号设置页']])g(password,['当前密码错误','校验成功后'],`公会修改密码：${expected}`,'公会密码提交校验',['当前密码为QaOld!2026'],[enter(password),`填写|当前密码|为${old}`,`填写|新密码|为${pwd}`,`填写|确认新密码|为${confirm}`,'点击|保存'],expected,P1);
g(password,['至少 8 位'],'公会新密码不足8位','公会新密码长度',['当前密码QaOld!2026'],[enter(password),'填写|当前密码|为QaOld!2026','填写|新密码|为Qa12345','填写|确认新密码|为Qa12345','点击|保存'],'不能保存不足8位的新密码',P1);
g(password,['请求失败'],'公会改密请求失败显示提示','公会改密失败提示',['原密码正确，新密码满足要求','环境准备：改密请求返回失败'],[enter(password),'填写|当前密码|为QaOld!2026','填写|新密码|为QaNew!2026','填写|确认新密码|为QaNew!2026','点击|保存'],'提示“保存失败”',ERR);
const ops='guild-operation-accounts.html',create='guild-operation-account-compose.html',op='guild-operation-account-detail.html',gifts='guild-operation-gift-records.html';
g(ops,['按运营账号名称或账号 ID 匹配'],'按账号ID搜索运营账号','运营账号ID搜索',['当前公会账号甲ID为9001，乙ID为9002'],[enter(ops),'输入|搜索框|为9001'],'搜索结果仅显示甲',P2);
g(ops,['本月剩余可发'],'公会当月额度用尽时显示零','公会剩余额度下限',['本月发放上限1000金币且已成功发放1000金币'],[enter(ops)],'本月剩余可发显示0金币',P1);
g(ops,['账户余额累计'],'汇总全部运营账号余额','公会虚拟币总余额',['公会运营账号甲余额100金币，乙200金币'],[enter(ops)],'账户余额累计 = 300',{...P1,calc:calculation('甲余额+乙余额',{甲余额:100,乙余额:200},{运算:'+',参数:[{变量:'甲余额'},{变量:'乙余额'}]},300)});
for(const field of ['头像','名称','账号','初始密码'])g(create,[`${field}：`],`创建运营账号必填${field}`,`运营账号${field}必填`,['其他创建字段合法且已填写'],[enter(create),`清空|${field}`,'点击|确认创建'],`不能创建缺少${field}的账号`,P1);
for(const field of ['名称','账号'])g(create,[`${field}：`],`运营账号${field}超过30字符`,`运营账号${field}长度`,[],[enter(create),`填写|${field}|为30个A`,`输入|${field}|末尾追加B`],`${field}不接受超过30字符`,P1);
for(const format of ['JPG','PNG','WebP'])g(create,['头像：'],`运营账号头像支持${format}`,'运营账号头像预览',[`准备有效qa.${format.toLowerCase()}图片`],[enter(create),`上传|头像|选择qa.${format.toLowerCase()}`],'显示所选头像预览',P2);
g(create,['全平台唯一'],'其他公会已占用账号不能重建','运营登录账号唯一性',['公会B已有有效登录账号L；当前公会A创建资料均合法'],[enter(create),'填写|账号|为L','点击|确认创建'],'不能创建重复登录账号',P1);
g(create,['至少 6 位'],'运营账号初始密码5位不通过','运营初始密码最小长度',['其他资料已填写'],[enter(create),'填写|初始密码|为Qa123','点击|确认创建'],'不能创建密码不足6位的账号',P1);
g(create,['默认启用'],'创建运营账号默认启用','运营账号初始状态',[],[enter(create)],'账号状态默认为启用',P2);
g(create,['默认 0'],'初始发放虚拟金币默认零','运营账号初始发放额',[],[enter(create)],'发放金币默认为0',P2);
for(const [account,guild,max]of [[100,200,100],[300,200,200],[100,0,0]])g(create,['较小值'],`账号剩余${account}公会剩余${guild}时发放上限`,'双额度取小值',[`账号月剩余额度${account}金币，公会月剩余额度${guild}金币`],[enter(create)],`最多可发放显示${max}金币`,P1);
for(const amount of [-1,101])g(create,['非负且不超过本次可发额度'],`初始发放${amount}金币不合法`,'初始发放额度校验',['本次最多可发放100金币，其他资料合法'],[enter(create),`填写|发放金币|为${amount}`,'点击|确认创建'],'不能创建额度不合法的账号',P1);
// Q-005: a successful creation needs a concrete valid login name. Keep that
// branch pending rather than pretending "valid format" is executable test data.
g(op,['平台锁定时仅可查看'],'平台锁定后公会运营账号只读','运营账号公会管理锁定',['平台已锁定该账号公会管理权限'],[enter(op)],'管理操作隐藏或不可用',{...P1,transition:'ST-ops-lock'});
g(op,['历史记录和余额保留'],'禁用运营账号保留余额','禁用运营账号余额',['运营账号启用且余额100金币，管理权限未锁定'],[enter(op),'禁用|账号状态开关'],'账户余额仍为100金币',{...P1,transition:'ST-ops-disable'});
g(op,['重新启用后恢复'],'重新启用已禁用运营账号','运营账号恢复启用',['当前运营账号禁用，管理权限未锁定'],[enter(op),'启用|账号状态开关'],'账号状态显示启用',{...P1,transition:'ST-ops-enable'});
g(op,['发放成功后刷新指标'],'发放虚拟金币后余额更新','运营账号发放后余额',['余额100金币，可发上限200金币，权限未锁定'],[enter(op),'填写|发放数量|为50','点击|发放金币'],'账户余额 = 150',{...P1,calc:calculation('原余额+发放额',{原余额:100,发放额:50},{运算:'+',参数:[{变量:'原余额'},{变量:'发放额'}]},150),transition:'ST-ops-issue'});
g(op,['共同限制'],'发放虚拟金币超公会剩余额度','运营账号发放超额限制',['账号月剩余100金币，公会月剩余50金币，权限未锁定'],[enter(op),'填写|发放数量|为51','点击|发放金币'],'不能完成超额发放',P1);
g(op,['默认本月'],'运营账号消费默认本月','运营账号默认消费周期',[],[enter(op)],'快捷日期默认本月',P2);
g(op,['带入账号和日期'],'按日消费进入送礼记录','运营送礼下钻条件',['正在查看账号甲，列表有9月15日消费'],[enter(op),'点击|9月15日消费行'],'送礼记录按账号甲和9月15日筛选',P2);
g(gifts,['默认全部运营账号、今日'],'运营送礼记录默认范围','运营送礼默认筛选',[],[enter(gifts)],'筛选范围为全部运营账号的今日记录',P2);
g(gifts,['单价 × 数量'],'运营送礼消费按单价件数计算','运营送礼消费金额',['成功记录单价10虚拟金币，赠送20件'],[enter(gifts),'点击|该送礼记录'],'消费金币 = 200',{...P1,calc:calculation('单价×数量',{单价:10,数量:20},{运算:'*',参数:[{变量:'单价'},{变量:'数量'}]},200)});
g(gifts,['成功送礼记录数'],'运营送礼次数不按件数统计','运营成功送礼笔数',['筛选范围内2笔成功送礼各10件，1笔失败'],[enter(gifts)],'总送礼次数显示2',P1);
const accounts='guild-operation-account-select.html';
g(accounts,['全选作用于全部运营账号'],'搜索后全选仍作用全部运营账号','运营账号全选范围',['共3个运营账号，搜索QA仅命中1个'],[enter(accounts),'输入|搜索框|为QA','点击|全选'],'已选数量显示3',P1);
g(accounts,['取消全选清空选择'],'取消运营账号全选','运营账号清空选择',['当前全部运营账号已选'],[enter(accounts),'点击|取消全选'],'已选数量显示0',P2);
g(accounts,['保留日期条件'],'选择运营账号后保留送礼日期','运营送礼筛选保留',['送礼记录已选9月1日至9月15日'],[enter(accounts),'选择|运营账号甲','选择|运营账号乙','点击|完成'],'送礼记录日期仍为9月1日至9月15日',P2);
const performance='guild-host-list.html',summary='guild-host-summary.html',records='guild-host-data.html',session='guild-live-gift-detail.html',income='guild-income.html',day='guild-income-day-detail.html';
g(performance,['直播发生时的公会关系'],'退会主播保留原公会期间业绩','公会历史业绩归属',['甲在公会A产生收益100，退出A加入B后产生200，当前查看A'],[enter(performance)],'甲在A的收益显示100金币',P1);
g(performance,['至少完成 1 场直播的去重主播数'],'周期内同主播多场只算1人','公会开播人数去重',['周期内甲完成2场，乙完成1场'],[enter(performance)],'开播人数显示2',P1);
g(summary,['新增关注人数，不扣除取关'],'新增粉丝不抵减取关人数','公会主播新增粉丝口径',['目标日新增10关注，取关3人'],[enter(summary)],'该日新增粉丝显示10人',P1);
for(const [mins,flag]of [[179,'未达标'],[180,'达标'],[181,'达标']])g(summary,['满 3 小时'],`主播日累计${mins}分钟有效天`,'主播有效天边界',[`目标日有效直播累计${mins}分钟`],[enter(summary)],`该日有效天标记为${flag}`,P1);
g(summary,['月数据当前无月份筛选控件'],'主播月数据不出现未定义筛选','主播月数据入口范围',[],[enter(summary),'切换|月数据'],'不显示月份筛选控件',P2);
g(summary,['带入主播和对应日期或月份'],'主播月数据下钻直播记录','主播月数据下钻条件',['当前对象为主播甲，9月有数据'],[enter(summary),'切换|月数据','点击|9月数据行'],'直播记录按甲和9月筛选',P2);
g(records,['按开播时间倒序'],'直播记录按开播先后排序','公会直播记录顺序',['同一日甲10点开播，乙12点开播'],[enter(records)],'12点场次排列在10点场次前',P2);
g(records,['重复进入只计 1 人'],'直播观众重复进入去重','场次观众去重',['用户甲进出3次、乙进入1次'],[enter(records)],'该场次观众显示2人',P1);
g(records,['不是送礼人数'],'场次收礼数量按件统计','场次收礼件数',['2名用户分别送10件和20件礼物'],[enter(records)],'该场次收礼数量显示30件',P1);
g(records,['每次开播创建一个新场次'],'同一主播重复开播保留不同场次','公会直播场次区分',['同一主播同日先后开播2次，第一次已结束'],[enter(records)],'列表保留两条不同场次记录',P1);
g(records,['带入主播 ID、日期和场次 ID'],'直播场次下钻绑定正确对象','公会场次详情定位',['列表含同主播同日两场记录A和B'],[enter(records),'点击|场次B'],'详情显示场次B的ID',P2);
g(session,['成功送礼的去重用户数'],'同一用户多笔送礼去重','场次送礼观众人数',['甲成功送礼2笔、乙1笔、丙失败1笔'],[enter(session)],'送礼观众显示2人',P1);
g(session,['普通礼物、定制礼物按成功实际消费金币计入'],'普通礼物和定制礼物计入主播收益','公会查看普通定制收益',['该场仅普通礼物实际消费100金币、定制礼物200金币'],[enter(session)],'礼物收益 = 300',{...P1,calc:calculation('普通礼物消费+定制礼物消费',{普通礼物消费:100,定制礼物消费:200},{运算:'+',参数:[{变量:'普通礼物消费'},{变量:'定制礼物消费'}]},300)});
for(const award of [0,1000])g(session,['默认 1%，返奖不影响主播收益'],`幸运礼物返奖${award}时主播收益`,'公会查看幸运礼物收益',[`本场仅一笔幸运礼物价值1000金币，快照比例1%，返奖${award}金币`],[enter(session)],'礼物收益 = 10',{...P1,calc:calculation('礼物价值×比例',{礼物价值:1000,比例:0.01},{运算:'*',参数:[{变量:'礼物价值'},{变量:'比例'}]},10)});
g(session,['运营账号赠送的礼物不计入主播实际收益'],'运营赠礼不增加主播收益','公会查看运营赠礼收益',['该场仅运营账号成功送出1000虚拟金币礼物'],[enter(session)],'礼物收益显示0金币',P1);
g(session,['返回时保留主播和日期筛选条件'],'场次详情返回保留筛选','公会直播记录返回筛选',['列表已按主播甲和9月15日筛选'],[enter(session),'返回|直播记录'],'筛选仍为主播甲和9月15日',P2);
for(const mode of ['日数据','月数据']){
 g(income,['去重主播数'],`${mode}跨日期统计去重开播人数`,`公会${mode}开播去重`,['选中范围内首日甲乙开播、次日乙丙开播，无其他开播主播'],[enter(income),`切换|${mode}`],'开播人数显示3',P1);
 g(income,['有效天总数'],`${mode}累计主播有效天`,`公会${mode}有效天统计`,['范围内甲2个有效天、乙3个有效天'],[enter(income),`切换|${mode}`],'达成有效天显示5天',P1);
}
g(income,['不是全部历史'],'公会月业绩按所选月份统计','公会月份过滤',['本月收益100金币，上月200金币，去年1000金币'],[enter(income),'切换|月数据','选择|自定义月份|为本月'],'公会收益显示100金币',P1);
g(income,['带入日期'],'公会日业绩下钻主播业绩','公会日业绩下钻日期',['日数据存在9月15日记录'],[enter(income),'点击|9月15日数据行'],'主播业绩筛选日期为9月15日',P2);
g(day,['当日收益倒序'],'已开播主播按收益排序','当日主播收益排序',['甲收益100金币、乙200金币'],[enter(day),'切换|已开播'],'乙排列在甲之前',P2);
g(day,['查看历史日期时为当日开播主播数'],'历史每日页直播中统计历史开播','历史日期开播人数',['历史日甲乙开播，当前只有丙在播'],[enter(day)],'直播中显示2人',P1);
g(day,['未开播不显示业绩'],'未开播列表不显示虚构收益','未开播主播业绩展示',['主播甲目标日未开播'],[enter(day),'切换|未开播'],'甲不显示当日业绩',P2);
const violation='guild-all-violations.html';
for(const scope of ['直播间违规','账号违规'])g(violation,['违规范围'],`按${scope}筛选违规记录`,`公会${scope}范围`,['当前公会两类违规各有记录'],[enter(violation),`选择|违规范围|为${scope}`],`只显示${scope}记录`,P1);
g(violation,['无处置结果显示'],'未处置违规不显示虚假结果','公会未处置违规结果',['违规记录尚无处置结果'],[enter(violation)],'处理结果显示“-”',P2);
for(const [page,entity]of [['guild-share-ledger.html','主播'],['guild-share-income.html','公会']]){
 for(const amount of ['12.30','-2.50'])g(page,['USD 金额'],`${entity}分成展示${amount}美元`,`${entity}财务分成金额`,[`平台已上传当前${entity}的${amount}USD有效结果`],[enter(page)],`分成金额显示${amount}美元`,P1);
 g(page,['按分成时间倒序'],`${entity}分成按入账时间排序`,`${entity}分成记录顺序`,['8月收益9月15日入账，9月收益9月14日入账'],[enter(page)],'9月15日入账记录排列在9月14日记录之前',P1);
}
g('guild-share-ledger.html',['按分成时间筛选'],'主播分成跨月按入账时间筛选','主播分成日期口径',['8月收益的分成9月15日入账'],[enter('guild-share-ledger.html'),'选择|自定义日期|为9月15日'],'列表包含该8月收益的分成记录',P1);
g('guild-share-income.html',['仅展示当前公会'],'公会分成隔离其他公会','公会分成查看范围',['当前公会A和公会B各有财务上传结果'],[enter('guild-share-income.html')],'不显示公会B的分成记录',P1);
g('guild-violation-host-select.html',['支持多选'],'选择多名主播回填筛选','公会数据多主播选择',['从直播记录进入选择页，已有日期条件9月15日'],[enter('guild-violation-host-select.html'),'选择|主播甲','选择|主播乙','点击|完成'],'已选主播为甲和乙',P2);
