import {page,lifecycle,computed,v,op,model} from './design-current.mjs';
const G='公会App',U='用户App',A='管理后台';
const login=page(G,'guild-login.html',['当前未登录；平台已创建公会长账号 guild_qa，密码 Guild#2026']);
for(const [account,password,success] of [['guild_qa','Guild#2026',true],['guild_qa','Wrong#2026',false],['unknown_qa','Guild#2026',false]])login.add(success?'公会长账号登录成功':'错误账号或密码拒绝登录',[],['打开公会登录',`输入公会账号 ${account}`,`输入密码 ${password}`,'点击登录'],[{point:'公会长登录凭证',result:success?'进入选择公会页':'提示“账号或密码错误”'}],[/登录|错误/]);
for(const field of ['公会账号','密码'])login.add(`${field}为空不能登录`,[],['打开公会登录',`清空${field}`,'点击登录'],[{point:`${field}必填`,result:'未进入选择公会页'}],[new RegExp(field),/必填/]);
for(const state of ['账号被停用','使用运营账号'])login.add(`${state}登录公会端`,[`本条账号属于${state}`],['打开公会登录','输入该测试账号和有效密码','点击登录'],[{point:'公会端账号准入',result:'未进入选择公会页'}],[/停用|运营账号|公会长/]);
const sw=page(G,'guild-switch.html',['公会长甲可管理公会甲和公会乙，当前选择公会甲；公会丙已解散']);
sw.add('切换公会更新数据归属',[],['打开选择公会','选择公会乙'],[{point:'当前公会切换',result:'首页公会名称显示公会乙'}],[/选择公会|更新/]);
sw.add('已解散公会不可选择',[],['打开选择公会'],[{point:'可管理公会范围',result:'可选列表不包含公会丙'}],[/解散/]);
sw.add('当前公会标记表示选择状态',[],['打开选择公会'],[{point:'当前公会标记',result:'只有公会甲显示“当前公会”'}],[/当前公会/]);
const home=page(G,'guild-home.html',['当前公会为公会甲；主播乙和丙属于公会甲']);
home.add('公会当日收益使用主播收益金币',['乙普通礼物收益 100、丙定制礼物收益 200，幸运礼物价值 1000 且收益比例 1%，虚拟送礼价值 500'],['打开公会首页','查看当日收益'],[computed('当日收益','普通收益 + 定制收益 + 幸运价值 × 比例',{普通收益:100,定制收益:200,幸运价值:1000,比例:0.01},op('+',v('普通收益'),v('定制收益'),op('*',v('幸运价值'),v('比例'))))],[/当日收益|幸运|虚拟/]);
home.add('公会直播中人数按主播去重',['当前乙在直播，丙未开播；乙当天此前另有已结束场次'],['打开公会首页','查看直播中'],[{point:'当前开播人数',result:'直播中显示 1 人'}],[/直播中/]);
for(const seconds of [10799,10800,10801])home.add(`每日有效直播 ${seconds} 秒的有效天判定`,[`公会甲当天只有主播乙，已核实有效直播累计 ${seconds} 秒`],['打开公会首页','查看达成有效天人数'],[{point:'三小时有效天门槛',result:`达成有效天显示 ${seconds>=10800?1:0} 人`}],[/3 小时|有效天/]);
const notices=page(G,'guild-notifications.html',['公会甲通知 N001 生成时间 10:00、N002 生成时间 11:00，均未读']);
notices.add('公会通知按生成时间倒序',[],['打开通知消息'],[{point:'公会通知排序',result:'N002 排在 N001 前面'}],[/倒序/]);
const nd=page(G,'guild-notification-detail.html',['公会甲通知 N001 当前未读，关联入会申请 J001']);
nd.add('进入公会通知详情标记已读',[],['打开通知 N001 详情','返回通知列表'],[{point:'公会通知阅读状态',result:'N001 不再显示未读圆点'}],[/已读/],{support:[/未读通知显示圆点/]});
for(const access of [true,false])nd.add(`通知关联记录${access?'有':'无'}访问权限`,[`当前公会长对 J001 ${access?'具有':'不具有'}访问权限`],['打开通知 N001 详情'],[{point:'通知业务入口权限',result:access?'显示关联业务入口':'不显示关联业务入口'}],[/权限|业务入口/]);
const msg=page(G,'guild-message-compose.html',['公会甲有当前主播乙和丙，前主播丁已退出']);
for(const n of [0,1,499,500,501])msg.add(`运营消息文字 ${n} 字符`,[],['打开新建运营消息','选择全体主播',n?`输入 ${n} 个“测”`:'清空文字内容','点击发送'],[{point:'运营消息文字长度',result:n>0&&n<=500?'显示接收范围二次确认':'未进入接收范围确认'}],[/500|文字|必填/]);
for(const format of ['JPG','PNG','WebP'])msg.add(`运营消息附带 ${format} 图片`,[],['打开新建运营消息','选择全体主播','输入“公会运营测试”',`上传一张 ${format} 测试图片`],[{point:'运营消息图片格式',result:'显示所选图片预览'}],[/图片/]);
msg.add('运营消息仅发送给当前主播',[],['打开新建运营消息','选择全体主播','输入“公会运营测试”','点击发送'],[{point:'运营消息接收范围',result:'确认接收人数为 2'}],[/全体|人数|当前/]);
const messageFlow=lifecycle('公会运营消息','待发送','确认发送运营消息','生成接收快照及通知','公会长',G,[G,U]);
msg.add('确认运营消息生成记录',[],['打开新建运营消息','选择全体主播','输入“公会运营测试”','点击发送','确认接收范围'],[{point:'运营消息发送记录',result:'运营消息列表新增“公会运营测试”记录'}],[/发送|生成记录/],{flow:messageFlow.流程编号,transition:messageFlow.状态转换标识});
const hostNotice=page(U,'host-guild-notifications.html',['主播乙属于公会甲，公会长已向乙发送“公会运营测试”']);
hostNotice.add('主播收到公会运营消息',[],['打开公会通知'],[{point:'主播接收公会消息',result:'通知列表包含“公会运营测试”'}],[/通知|消息/],{flow:messageFlow.流程编号,transition:messageFlow.状态转换标识});
const msgDetail=page(G,'guild-message-detail.html',['消息 M001 发送时接收人为乙和丙，共 2 人，正文“公会运营测试”；丙在发送后退会']);
msgDetail.add('接收人退会不改变消息历史快照',[],['打开 M001 运营消息详情'],[{point:'历史接收人数',result:'接收人数仍为 2'},{point:'历史接收人',result:'接收人中仍有丙'},{point:'消息详情不可撤回',result:'详情不提供编辑或撤回操作'}],[/快照|只读|退会|人数/],{support:[/发送后不支持编辑或撤回/]});
const hostSelect=page(G,'guild-host-select.html',['公会甲当前主播乙 ID 1001、丙 ID 1002，其他公会有主播丁']);
for(const term of ['乙','1001'])hostSelect.add(`指定主播用${term}搜索`,[],['打开选择主播',`输入搜索词 ${term}`],[{point:'当前公会主播检索',result:'结果包含主播乙'}],[/搜索/]);
hostSelect.add('运营消息只能指定一名主播',[],['打开选择主播','选择主播乙','选择主播丙'],[{point:'指定主播单选',result:'只有主播丙处于选中状态'}],[/仅可选 1 人/]);
hostSelect.add('没有选择主播不能完成',[],['打开选择主播','点击完成'],[{point:'指定主播必选',result:'提示选择主播'}],[/未选择/]);
const create=page(G,'guild-operation-account-compose.html',['公会甲未被锁定运营账号管理；登录账号 qa_ops_9001 全平台未使用；头像 ops.png，名称“测试运营”，初始密码 Ops#2026；本次可发额度 100']);
for(const field of ['头像','名称','账号','初始密码'])create.add(`创建运营账号的${field}为空`,[],['打开创建运营账号',field==='头像'?'删除头像':`清空${field}`,'点击确认创建'],[{point:`运营账号${field}必填`,result:'未创建运营账号'}],[new RegExp(field),/必填/]);
for(const field of ['名称','账号'])for(const n of [29,30,31])create.add(`运营账号${field}为 ${n} 字符`,[],['打开创建运营账号',`输入 ${n} 个字母 a 作为${field}`,'点击确认创建'],[{point:`${field}长度上界`,result:n<=30?'运营账号创建成功':`未使用 ${n} 字符${field}创建账号`}],[new RegExp(field)]);
for(const n of [5,6,7])create.add(`运营账号初始密码 ${n} 位`,[],['打开创建运营账号',`输入初始密码 ${'A'.repeat(n)}`,'点击确认创建'],[{point:'运营账号密码最小长度',result:n>=6?'运营账号创建成功':'未创建运营账号'}],[/初始密码/]);
for(const amount of [-1,0,99,100,101])create.add(`运营账号初始发放 ${amount} 金币`,[],['打开创建运营账号',`输入发放金币 ${amount}`,'点击确认创建'],[{point:'创建初始发放边界',result:amount>=0&&amount<=100?'运营账号创建成功':'未创建运营账号'}],[/发放金币|可发|额度/]);
create.add('运营账号登录账号全平台唯一',['其他公会已使用 qa_ops_9001'],['打开创建运营账号','输入账号 qa_ops_9001','点击确认创建'],[{point:'运营账号全局唯一',result:'未创建第二个 qa_ops_9001 账号'}],[/账号|唯一/]);
const ops=page(G,'guild-operation-account-detail.html',['公会甲运营账号 O001 可用，虚拟余额 100，账号本月剩余额度 200、公会本月剩余额度 150']);
ops.add('发放上限取两个剩余额度较小值',[],['打开 O001 运营账号主页','查看可发上限'],[computed('可发上限','min(账号剩余额度,公会剩余额度)',{账号剩余额度:200,公会剩余额度:150},op('min',v('账号剩余额度'),v('公会剩余额度')))],[/较小值|发放上限/]);
const issue=lifecycle('虚拟金币发放','在月度额度内','公会发放虚拟金币','增加虚拟余额并占用月额度','公会长',G,[G,A,U]);
for(const amount of [149,150,151])ops.add(`可发150时发放 ${amount}`,[],['打开 O001 运营账号主页',`输入发放数量 ${amount}`,'确认发放'],[amount<=150?computed('虚拟金币余额','原余额 + 发放数量',{原余额:100,发放数量:amount},op('+',v('原余额'),v('发放数量'))):{point:'月度可发上限',result:'未新增发放流水'}],[/发放|余额/],{flow:issue.流程编号,transition:amount<=150?issue.状态转换标识:undefined});
ops.add('平台锁定后公会不能管理运营账号',['平台已锁定公会甲运营账号管理权限'],['打开 O001 运营账号主页'],[{point:'锁定后的启停权限',result:'账号启停操作不可用'},{point:'锁定后的发放权限',result:'发放金币操作不可用'}],[/锁定/]);
ops.add('禁用运营账号保留余额历史',[],['打开 O001 运营账号主页','禁用账号','确认禁用'],[{point:'禁用后虚拟余额',result:'虚拟金币余额仍为 100'},{point:'禁用后历史记录',result:'原送礼记录仍可查看'}],[/禁用后|保留/]);
const issueA=page(A,'admin-operation-issue-records.html',['公会甲刚向 O001 成功发放 150 金币，发放前余额 100，操作人为公会长甲']);
issueA.add('后台追溯公会虚拟金币发放',[],['打开发放记录','查询运营账号 O001'],[{point:'发放执行者归属',result:'本次发放操作人显示公会长甲'},computed('发放后余额','发放前余额 + 发放金币',{发放前余额:100,发放金币:150},op('+',v('发放前余额'),v('发放金币')))],[/操作人|余额|发放金币/],{flow:issue.流程编号,transition:issue.状态转换标识});
const issueU=page(U,'profile.html',['当前执行者为公会甲运营账号 O001；公会刚发放 150 虚拟金币，原余额 100']);
issueU.add('运营账号查看公会发放后的余额',[],['打开我的','查看金币余额'],[computed('虚拟金币余额','原余额 + 公会发放金币',{原余额:100,公会发放金币:150},op('+',v('原余额'),v('公会发放金币')))],[/运营账号|余额|虚拟/],{role:'运营账号',flow:issue.流程编号,transition:issue.状态转换标识});
const selector=page(G,'guild-operation-account-select.html',['公会甲有运营账号 O001、O002，名称分别运营甲、运营乙；账号均未选择']);
selector.add('搜索后全选仍选中全部运营账号',[],['打开选择运营账号','搜索运营甲','点击全选'],[{point:'全选作用范围',result:'O001 和 O002 均已选择'}],[/全选/]);
selector.add('取消全选清空已选账号',['O001 和 O002 已选择'],['打开选择运营账号','取消全选'],[{point:'取消全选范围',result:'已选账号数量为 0'}],[/取消全选/]);
const guildProfile=page(G,'guild-profile.html',['当前公会为公会甲，名称“原公会名”，简介“原简介”']);
for(const [field,max] of [['公会名称',40],['公会简介',200]])for(const n of [0,1,max,max+1])guildProfile.add(`${field}输入 ${n} 字`,[],['打开公会资料',n?`输入 ${n} 个“测”作为${field}`:`清空${field}`,'点击保存'],[{point:`${field}长度范围`,result:n<=max&&(n>0||field==='公会简介')?`${field}保存为${n?`${n} 个“测”`:'空值'}`:'本次公会资料未保存'}],[new RegExp(field)]);
guildProfile.add('公会名称去除首尾空格',[],['打开公会资料','输入公会名称“  新公会名  ”','点击保存'],[{point:'公会名称空格处理',result:'公会名称保存为“新公会名”'}],[/空格/]);
const gs=page(G,'guild-settings.html',['公会长甲已登录，当前管理公会甲']);
for(const lang of ['中文','English','Bahasa Indonesia','Bahasa Melayu'])gs.add(`公会账号语言切换 ${lang}`,[],['打开账号设置',`选择语言 ${lang}`],[{point:'公会端语言选择',result:`当前语言显示 ${lang}`}],[/语言/]);
gs.add('公会账号退出登录',[],['打开账号设置','点击退出登录','确认退出'],[{point:'公会端退出会话',result:'返回公会登录页'}],[/退出登录/]);
const pass=page(G,'guild-password.html',['公会长甲当前密码为 Guild#2026']);
for(const [name,old,next,confirm,result] of [['旧密码错误','Wrong#2026','NewGuild#2026','NewGuild#2026','提示“当前密码错误”'],['新旧相同','Guild#2026','Guild#2026','Guild#2026','提示“新密码不能和旧密码一样”'],['两次新密码不同','Guild#2026','NewGuild#2026','Other#2026','未保存新密码']])pass.add(`公会密码修改${name}`,[],['打开修改密码',`输入当前密码 ${old}`,`输入新密码 ${next}`,`输入确认新密码 ${confirm}`,'点击保存'],[{point:'公会密码修改校验',result}],[/密码|一致|错误/]);
pass.add('公会密码修改请求失败',['测试环境保存密码请求失败'],['打开修改密码','输入当前密码 Guild#2026','输入新密码 NewGuild#2026','输入确认新密码 NewGuild#2026','点击保存'],[{point:'公会密码失败提示',result:'提示“保存失败”'}],[/请求失败/]);
// Date filters share explicit inclusive endpoints, but each page keeps its own data type and source.
for(const p of Object.values(model.pages).filter(p=>p.endName===G)){
 const rs=model.requirements.filter(r=>r.page===p.key&&/包含开始日和结束日/.test(r.body));if(!rs.length)continue;
 const pg=page(G,p.原型页面,['有业务记录 A 在 09/01 00:00、B 在 09/02 23:59、C 在 08/31、D 在 09/03，均属于当前公会及本页对应记录类型']);
 pg.add(`${p.name}自定义日期包含起止日`,[],[`打开${p.name}`,'选择自定义日期 09/01 至 09/02','确认筛选'],[{point:'日期起点包含',result:'列表包含记录 A'},{point:'日期终点包含',result:'列表包含记录 B'},{point:'日期范围外排除',result:'列表不包含记录 C 和 D'}],[],{sourceIds:rs.map(r=>r.id)});
}
