import {transition,transitions,save} from './model.mjs';
export const states={};
const add=(key,...args)=>states[key]=transition(...args);
add('joinSubmit','入会认证申请','未入会且无处理中申请','提交入会申请','用户','用户App','待公会初审',['用户App','公会App'],'guild-application-form.html',/生成处理中申请/);
add('guildApprove','入会认证申请','待公会初审','同意入会申请','公会长','公会App','待平台终审',['用户App','公会App','管理后台'],'guild-join-review-detail.html',/平台|通过/);
add('guildReject','入会认证申请','待公会初审','驳回入会申请','公会长','公会App','申请失效且未入会',['用户App','公会App'],'shared',/驳回.*申请|申请.*驳回/,'驳回');
add('platformApprove','入会认证申请','待平台终审','通过认证终审','平台管理员','管理后台','已加入公会并具有主播身份',['用户App','公会App','管理后台'],'admin-host-review-detail.html',/通过后加入/);
add('platformReject','入会认证申请','待平台终审','驳回认证终审','平台管理员','管理后台','申请失效且未入会',['用户App','公会App','管理后台'],'shared',/驳回.*申请|申请.*驳回/,'驳回');
add('leaveSubmit','公会成员关系','已加入且无处理中退会申请','提交退会申请','主播','用户App','退会审核中且保留成员关系',['用户App','公会App'],'guild-leave-application.html',/生成处理中申请/);
add('leaveReject','公会成员关系','退会审核中且保留成员关系','驳回退会申请','公会长','公会App','已加入且无处理中退会申请',['用户App','公会App'],'guild-leave-application.html',/公会驳回/,'驳回');
add('leaveApprove','公会成员关系','退会审核中且保留成员关系','通过退会申请','公会长','公会App','已退会且失去主播身份',['用户App','公会App','管理后台'],'guild-leave-application.html',/退会申请通过/);
add('guildDisable','公会组织','启用且有在会主播','停用公会','平台管理员','管理后台','公会停用且主播关系已解除',['用户App','公会App','管理后台'],'shared',/停用|旗下主播/);
add('ban','账号','可登录','封禁账号','平台管理员','管理后台','禁止登录且当前直播已结束',['用户App','管理后台'],'admin-user-list.html',/封禁后/);
add('liveStart','直播场次','未开播且满足开播条件','开始直播','主播','用户App','新场次直播中',['用户App','公会App','管理后台'],'start-live-settings.html',/已授权时创建新场次/);
add('liveEnd','直播场次','直播中','确认结束直播','主播','用户App','场次已结束',['用户App','公会App','管理后台'],'views/live-room-host/end-confirm.html',/结束直播会|确认 ->/);
add('closePermission','主播直播权限','账号公会认证有效且直播中','关闭平台直播权限','平台管理员','管理后台','无开播权限且当前场次已结束',['用户App','公会App','管理后台'],'admin-host-list.html',/平台关闭直播权限/);
add('charge','充值订单','待支付','支付充值订单','用户','用户App','支付成功且金币入账',['用户App','管理后台'],'recharge.html',/支付成功/);
add('refund','充值订单','支付成功且未退款','确认全额退款','平台管理员','管理后台','已退款且扣回原到账金币',['用户App','管理后台'],'admin-recharge-order-detail.html',/退款|扣回/);
add('sendGift','金币消费订单','余额充足且礼物可赠送','赠送礼物','观众','用户App','赠送成功且只扣减一次金币',['用户App','公会App','管理后台'],'views/live-room/gift.html',/余额充足/);
add('operationCreate','运营账号','账号不存在且公会有管理权限','创建运营账号','公会长','公会App','账号已创建',['用户App','公会App','管理后台'],'guild-operation-account-compose.html',/创建|账号/);
add('operationGrant','运营账号虚拟金币','剩余额度足够','发放虚拟金币','公会长','公会App','虚拟余额增加并占用月度额度',['用户App','公会App','管理后台'],'guild-operation-account-detail.html',/发放/);
add('settlementUpload','线下分成批次','导入校验通过且未确认','确认导入分成结果','平台管理员','管理后台','结果已入账且不可改删',['用户App','公会App','管理后台'],'admin-settlement-record.html',/确认|上传后/);
add('reportSubmit','直播举报工单','场次直播中','提交直播举报','观众','用户App','待处理',['用户App','管理后台'],'live-room-report.html',/提交成功/);
add('reportEnd','直播举报工单','待处理','结束被举报场次','主播','用户App','举报已作废',['管理后台'],'live-room-report.html',/场次结束后.*失效/);
add('cohostInvite','主播连麦关系','双方普通房在播且未连麦','发送连麦邀请','主播','用户App','邀请待处理',['用户App'],'shared',/邀请连麦/);
add('cohostAccept','主播连麦关系','邀请待处理','接受连麦邀请','主播','用户App','两位主播连麦中',['用户App'],'views/live-room-host/cohost-invite-notice.html',/接受 ->/);
add('cohostExit','主播连麦关系','两位主播连麦中','确认退出连麦','主播','用户App','各自单人直播继续',['用户App'],'views/live-room-cohost-active/cohost-exit-confirm.html',/确认 ->/);
add('block','账号社交关系','双方已有社交关系','确认拉黑账号','用户','用户App','双向社交关系解除且拉黑限制生效',['用户App'],'views/user-home/block-confirm.html',/确认拉黑后/);
add('fanExit','粉丝团团籍','有效团籍','确认退出粉丝团','粉丝团成员','用户App','团籍群籍解除且等级亲密度归零',['用户App'],'group-manage-member.html',/主动退出/);
add('deletion','账号注销申请','余额低于100且未申请注销','等待注销确认倒计时结束','用户','用户App','七日冷静期',['用户App'],'settings.html',/倒计时结束/);
export async function freezeStates(){await save('state-transition-baseline.json',{schemaVersion:'1.0',建立顺序:'当前独立需求规则之后、场景之前',状态转换:transitions,闭环状态:'尚待端侧场景逐项映射，不以转换记录数量宣称覆盖完成'});}
