import {scenario as s,observe as o,navigation as nav,refs,textBoundary,numbers,required,context} from './design.mjs';
import {reviewed} from './basic-design.mjs';
import {flows} from './lifecycles.mjs';
const r=refs, f=k=>({flow:flows[k].flow,transition:flows[k].id});
for(const live of [true,false])o('U-my-fan-clubs-006',`粉丝团卡片直播标记${live?'显示':'隐藏'}`,[`所属主播当前${live?'正在':'没有'}直播`],`${live?'显示':'隐藏'}直播标记`);
s('U-my-fan-clubs-002','粉丝团主播头像不跳转',['当前有有效团籍'],['点击卡片上的主播头像'],'仍停留我的粉丝团页');
o('U-my-fan-clubs-005','重新入团更新加入日期',['上次入团为9月1日并已退出，本次于9月5日重新加入'],'加入日期显示9月5日');
o('U-my-fan-clubs-017','粉丝团按本次入团倒序',['两个有效团籍分别在9月1日和9月5日加入'],'9月5日加入的粉丝团在前');
for(const reason of ['退出','被移出','粉丝团解散'])o('U-my-fan-clubs-013',`${reason}移除团卡片`,[`原有有效团籍，随后发生${reason}`],'对应粉丝团卡片已移除');
for(const reason of ['主动退出','被主播移出'])for(const item of ['关注关系','粉丝等级','亲密度'])o('U-my-fan-clubs-014',`${reason}后的${item}`,[`该团原粉丝等级3级、亲密度10且已关注主播，随后${reason}`],item==='关注关系'?'仍关注该主播':`${item}清零`);
o('U-my-fan-clubs-004','粉丝团等级使用团累计值',['团累计收礼达团等级3级，当前成员个人贡献仅达粉丝1级'],'卡片团等级显示3级');
o('U-my-fan-clubs-008','个人粉丝等级按主播分别计算',['对主播甲贡献达粉丝2级，对主播乙达粉丝3级'],'甲卡片粉丝等级2级，乙卡片粉丝等级3级');
for(const [key,i] of [['贡献值',0],['当前团粉丝等级',1],['财富等级',2],['用户ID数字部分',3]])o('U-fan-contribution-ranking-004',`粉丝贡献榜${key}裁决`,[`两用户前${i}个排序键一致，${key}分别为10和20`],`${key.includes('ID')?'10':'20'}对应用户排在另一用户前`);
for(const count of [0,1,98,99,100])o('U-fan-contribution-ranking-005',`粉丝贡献榜${count}人上限`,[`本期已确定贡献数据中有${count}个排名用户`],`展示${Math.min(count,99)}条排名`);
o('U-fan-contribution-ranking-005','粉丝贡献榜99名同值',['第99及100名候选贡献相同，粉丝等级分别3和2'],'粉丝3级候选占第99名，另一个不进入榜单');
for(const name of ['粉丝等级','财富等级'])o('U-fan-contribution-ranking-007',`粉丝贡献榜${name}最低档`,['用户尚未达更高等级门槛'],`${name}显示1级`);
for(const period of ['本周','本月','累计'])s('U-fan-contribution-ranking-010',`粉丝贡献榜切换${period}`,['各周期已确定的有效统计结果不同'],[`选择${period}`],`前三名、榜单及我的排名刷新为${period}结果`);
for(const type of ['主播等级','财富等级','粉丝等级','粉丝团等级']){
  const opts={page:'admin-level-config.html'};
  for(const amount of [99,100,101,300])o('A-admin-level-config-012',`${type}累计值${amount}判级`,[`当前${type}配置为1级0、2级100、3级200、4级300金币`,`该对象累计值为${amount}`],`${type}判定为${amount<100?1:amount<200?2:4}级`,{...opts,type:'逻辑校验'});
  s('A-admin-level-config-011',`${type}修改门槛立即重算`,[`该类型对象累计150，原2级门槛100`],[`切换${type}Tab`,'将2级门槛改为200','保存当前Tab'],`该类型已有对象不再满足2级门槛`,opts);
  s('A-admin-level-config-015',`${type}新增连续编号`,[`当前${type}最高编号为3`],[`切换${type}Tab`,'点击新增等级'],'新增等级编号为4，金币数值为空',opts);
  s('A-admin-level-config-016',`${type}保存留在当前Tab`,['该类型全部数值及勋章图合法'],[`切换${type}Tab`,'点击保存'],`保存成功后仍停留${type}Tab`,opts);
}
o('A-admin-level-config-014','四类等级编号不可编辑',[],'各Tab等级从1连续递增且编号不可编辑');
o('A-admin-level-config-015','等级配置没有删除入口',[],'当前页不提供删除等级入口');
for(const value of ['',-1,0,1])s('A-admin-level-config-014',`等级门槛${value===''?'空值':value}`,['当前Tab其余等级配置和勋章图合法'],[value===''?'清空该等级金币数值':`填写该等级金币数值${value}`,'点击保存'],value===''||value<0?'当前Tab不能保存':'当前Tab接受该门槛值',{type:'逻辑校验'});
s('A-admin-level-config-016','切换等级Tab保留未保存输入',['当前主播等级有未保存数值及勋章图'],['切换财富等级Tab','切回主播等级Tab'],'主播等级未保存数值及图片保持不变');
s('A-admin-level-config-016','保存仅校验当前Tab',['主播等级Tab有合法修改','财富等级Tab存在未填写门槛'],['切到主播等级Tab','点击保存'],'主播等级Tab可保存，不受财富等级空值阻断');
for(const file of ['非图片文件','损坏图片'])s('A-admin-level-config-018',`勋章上传${file}`,['当前等级已有有效图片'],[`选择${file}`],'提示重新选择，原图片保留',{type:'异常用例'});
s('A-admin-level-config-018','勋章取消选择保留原图',['当前等级已有图片'],['打开图片选择','取消选择'],'原勋章图保持不变');
s('A-admin-level-config-017','勋章上传预览',['准备一张可读取图片'],['为当前等级选择该图片'],'当前等级显示所选图片预览');
s('A-admin-level-config-017','勋章图缺失阻止保存',['当前Tab某等级尚未上传勋章图'],['点击保存'],'提示缺图的对应等级并阻止保存',{type:'异常用例'});
o('A-admin-level-config-007','等级配置不发放资产',['已记录对象钱包与累计贡献','平台仅修改该对象所属等级门槛'],'对象钱包和累计贡献未因改门槛而增加');
for(const type of ['主播等级','财富等级','粉丝等级','粉丝团等级'])o('A-admin-level-config-013',`${type}排除虚拟金币`,['已记录该类型累计值','仅新增运营账号虚拟金币赠礼'],`${type}累计值保持不变`);

for(const count of [0,2,3])s(['U-moderator-management-003','U-moderator-management-009'],`房管已有${count}人添加`,[`当前有${count}名长期授权房管，目标用户未被拉黑且非房管`],['点击添加房管',...(count<3?['按目标用户ID搜索','确认添加该用户']:[])],count===3?'提示“已达3人上限”，房管仍为3人':`房管列表新增该用户，人数为${count+1}`);
for(const condition of ['在直播间黑名单','双方有账号拉黑','已经是房管'])s(['U-moderator-management-004','U-moderator-management-009'],`房管搜索排除${condition}`,[`目标用户${condition}`],['点击添加房管','搜索该用户ID'],'搜索结果不包含该用户');
for(const confirm of [true,false])s('U-moderator-management-009',`取消房管${confirm?'确认':'取消'}`,['已有该用户房管授权'],['点击取消房管',`点击${confirm?'确认':'取消'}`],confirm?'该用户立即移出房管列表':'该用户仍为房管');
o('U-moderator-management-006','结束场次保留长期房管',['该用户已授权房管，主播随后结束本场直播'],'该用户房管授权仍有效');
o('U-moderator-management-005','取消拉黑不恢复房管',['房管因双方拉黑自动解除，现已取消拉黑'],'该用户仍不在房管列表');
for(const reason of ['新增关注','取消关注','拉黑主播'])o(['U-fan-list-005','U-fan-list-007'],`主播粉丝列表${reason}`,['目标账号原始关系与该动作相符',`目标账号刚完成${reason}`],`粉丝列表${reason==='新增关注'?'包含':'不包含'}该账号`);
o('U-fan-list-004','粉丝装扮过期移除',['目标粉丝展示的代表性装扮刚过期'],'该装扮不再展示');
nav('U-fan-list-007','用户头像','对应用户主页');
for(const confirm of [true,false])s('U-fan-club-010',`移除粉丝成员${confirm?'确认':'取消'}`,['本团有2名有效成员'],['左滑目标成员','点击移除',`点击${confirm?'确认':'取消'}`],confirm?'目标成员移出，本团成员数为1':'目标成员仍在团，本团成员数为2',f('removeFan'));
for(const result of ['成功','取消','请求失败'])s('U-views_fan-club_member-mute-confirm-005',`粉丝群单人禁言${result}`,['目标成员原可在群内发言',...(result==='请求失败'?['禁言请求返回失败']:[])],[`点击${result==='取消'?'取消':'确认禁言'}`],result==='成功'?'该成员在当前粉丝群被禁言并提示成功':'该成员仍可在当前粉丝群发言');
for(const item of ['团籍','关注','直播间发言权限'])o('U-views_fan-club_member-mute-confirm-004',`粉丝群禁言不改${item}`,['目标成员已在当前粉丝群被单独禁言'],`原${item}保持不变`);
nav('U-fan-club-011','粉丝团设置','粉丝团设置');
textBoundary('U-fan-club-settings-002','粉丝团名称',20,{required:true});
for(const value of ['',-1,0,1,1.5])s(['U-fan-club-settings-004','U-fan-club-settings-007'],`入团门槛${value===''?'空值':value}`,['粉丝团名称合法'],[value===''?'清空累计贡献':`填写累计贡献${value}`],value!==''&&Number.isInteger(value)&&value>=0?'保存按钮可用':'保存按钮不可用',{type:'逻辑校验'});
s('U-fan-club-settings-005','提高门槛保留既有成员',['当前团成员贡献50，原门槛0'],['将累计贡献门槛改为100','保存'],'贡献50的既有成员不被移除');
s('U-fan-club-settings-008','保存新的入团条件',['当前为该团所属主播'],['将需要关注开启、累计贡献设为100','点击保存'],'当前团加入条件变为已关注且累计贡献至少100');

for(const [key,value] of [['名称','海岛'],['ID','100']])for(const method of ['实时输入','点击搜索','按Enter'])s(['U-guild-management-002','U-guild-management-011'],`公会按${key}${method}搜索`,[`可展示公会有${key}包含${value}及不包含${value}的记录`],[`输入「${value}」`,...(method==='实时输入'?[]:[method])],`仅显示${key}模糊匹配的可展示公会`);
s('U-guild-management-009','清空公会筛选',['当前存在搜索关键词'],['清空搜索框'],'展示全部本页配置范围内公会，包含已加入或申请中的公会');
s('U-guild-management-011','公会搜索无匹配',[],['输入一个不存在的公会名称'],'列表显示空状态');
o('U-guild-management-007','停用公会不展示不可搜索',['目标公会被平台停用'],'公会列表和搜索结果均不包含目标公会');
o('U-guild-management-008','公会搜索保留后台顺序',['后台配置顺序为公会甲、乙、丙，搜索同时匹配甲与丙'],'结果按甲、丙排列');
for(const status of ['已加入公会','有处理中入会申请'])o(['U-guild-management-010','U-guild-management-013'],`${status}禁止再次申请`,[status],'其他公会申请按钮置灰且不可点击');
nav('U-guild-management-012','申请','填写申请单',['账号无公会关系或处理中申请']);nav('U-guild-management-012','我的','我的公会');
o('U-guild-application-form-002','申请公会来源一致',['从公会选择页选中公会甲'],'申请公会显示公会甲');
for(const name of ['姓名','电话','本人照片','证件正面','证件反面'])s('U-guild-application-form-012',`入会申请缺少${name}`,['其余必填材料齐全'],[`保持${name}未填写或未上传`],'提交按钮不可用',{type:'异常用例'});
s('U-guild-application-form-003','入会姓名仅空格',['其余资料齐全'],['姓名输入3个空格'],'提交按钮不可用',{type:'异常用例'});
o('U-guild-application-form-006','默认KTP证件',[],'默认选中KTP，证件类型不可同时选择KTP和SIM');
for(const type of ['KTP','SIM'])s(['U-guild-application-form-006','U-guild-application-form-012'],`切换至${type}清空旧证件`,[`当前选中另一证件类型，正反面照片已上传`],[`选择${type}`],'证件正反面照片均清空，需重新上传');
for(const field of ['本人照片','证件正面','证件反面'])s(['U-guild-application-form-005','U-guild-application-form-007'],`${field}拒绝非图片`,[],[`为${field}选择文本文件`],`${field}不能使用该非图片文件`,{type:'异常用例'});
s(['U-guild-application-form-009','U-guild-application-form-013'],'首次提交入会申请',['未加入公会且没有处理中申请','姓名、+62电话、本人照片和所选证件正反面材料齐全'],['点击提交'],'生成一笔处理中申请并进入所选公会详情',f('join'));
nav('U-guild-application-form-014','更换公会','公会选择');
o('U-guild-application-records-006','我的公会保留历史',['当前账号有申请中、已加入、被驳回、已退出公会各一个'],'四类公会均保留，未申请过的公会不显示');
o('U-guild-application-records-007','同公会多次申请一张卡片',['当前账号对同公会曾两次入会和一次退会'],'该公会仅显示一张卡片');
o('U-guild-application-records-008','我的公会最近申请倒序',['公会甲最新入会申请早于公会乙最新退会申请'],'公会乙排在公会甲之前');
for(const [state,visible] of [['已加入且无退会申请',true],['退会申请中',false],['入会申请中',false],['入会已驳回',false],['已退出',false]])o('U-guild-detail-018',`${state}退出入口`,[`当前关系为${state}`],`${visible?'显示':'不显示'}申请退出入口`);
for(const state of ['退会申请中','退会已驳回','退会已通过'])o('U-guild-detail-016',`${state}关系状态`,[`当前最新退出申请为${state}`],`公会关系显示${state==='退会已通过'?'已退出':'已加入'}`);
for(const state of ['入会申请中','已加入','入会已驳回','退会申请中','退会已驳回','已退出'])o('U-guild-detail-017',`${state}保留申请快照`,[`公会关系/申请当前为${state}`,'申请时姓名为甲，个人资料后来改名为乙'],'展开的申请资料仍显示姓名甲且只读');
o('U-guild-detail-013','申请时间轴倒序',['同公会有两次入会和一次退出申请，提交时间不同'],'三笔申请按提交时间从新到旧排列');
for(const field of ['处理时间','申请原因','驳回原因'])for(const exists of [true,false])o(`U-guild-detail-${{处理时间:'006',申请原因:'007',驳回原因:'008'}[field]}`,`${field}${exists?'有值':'无值'}`,[`当前申请${field==='驳回原因'?'已驳回':field==='处理时间'?'已处理':''}且${field}${exists?'有':'无'}内容`],`${exists?'显示':'隐藏'}${field}`);
s('U-guild-detail-020','申请材料独立展开收起',['当前公会有两张加入申请单且默认均收起'],['展开第一张申请资料'],'仅第一张展开，第二张仍收起');
s('U-guild-detail-020','再次点击收起资料',['一张申请资料已展开'],['再次点击该单申请资料'],'该单资料收起');
nav('U-guild-detail-019','返回','我的公会');
for(const value of ['','   ','个人原因'])s(['U-guild-leave-application-003','U-guild-leave-application-008'],`退会原因${value.trim()?'有效':'空白'+value.length}`,['当前已在会且无处理中退会申请'],[value?`填写原因「${value}」`:'清空原因'],'提交按钮'+(value.trim()?'可用':'不可用'));
s('U-guild-leave-application-008','提交退会申请',['当前已在会、收益已结清且无处理中退会申请'],['填写“个人原因”','点击提交'],'生成一笔处理中退会申请',f('leave'));
s('U-guild-leave-application-005','退会被驳回可重新申请',['此前退会已驳回，当前仍有公会和主播身份'],['填写新的退会原因','点击提交'],'生成新的一笔处理中退会申请');
for(const cause of ['退会通过','公会移出'])for(const [item,page,result] of [['当前直播','live-room-host.html','当前场次立即结束'],['主播身份','profile.html','主播身份失效，主播中心入口进入申请成为主播页'],['粉丝团','fan-club.html','原粉丝团解散'],['成员团籍','my-fan-clubs.html','原团卡片消失'],['群聊权限','message-center.html','原粉丝群会话入口移除']])o('U-guild-leave-application-006',`${cause}影响${item}`,[`目标主播有在播场次及粉丝团，收益已结清，公会已完成${cause}`],result,{page,role:item.includes('成员')||item==='群聊权限'?'粉丝团成员':'主播',...f(cause==='退会通过'?'approveLeave':'removeHost')});
for(const type of ['纯文字','图片加文字'])o('U-host-guild-notifications-003',`主播接收${type}通知`,[`当前公会向主播发出有效${type}通知`],`通知卡片展示该${type}内容`);
s('U-host-guild-notifications-007','展开通知不跳详情',['当前公会有长内容通知'],['展开长内容'],'正文在当前通知卡片内展开，页面仍为公会通知');
s('U-host-guild-notifications-007','收起通知长内容',['长内容已展开'],['点击收起'],'正文恢复卡片收起状态');
o('U-host-guild-notifications-005','退会后不接收新公会通知',['主播已退会，原公会随后发出一条新通知'],'列表没有退会后发出的这条通知');
for(const age of [17,18,19])s('U-host-center-pending-014',`主播认证年龄${age}`,['处于可提交认证资料阶段，必填材料齐全',`认证年龄为${age}周岁`],['打开认证资料弹窗','提交资料'],age<18?'不能提交认证申请':'提交成功关闭弹窗，进入直播权限审核中');
o('U-host-center-pending-010','直播权限审核中禁重提',['当前申请直播权限审核中'],'公会显示已同意，权限显示申请中，不可重复提交或开播');
o('U-host-center-pending-009','公会驳回暂不能申请直播权限',['当前公会申请被驳回'],'允许重新选公会，但不能申请直播权限');

for(const [p,statuses] of [['G-guild-leave-review',['待审核','已通过','已驳回']],['G-guild-join-review',['审核中','已通过','已驳回']]])for(const state of statuses)s(`${p}-${p.includes('leave')?'006':'007'}`,`${p.includes('leave')?'退会':'入会'}筛选${state}`,['存在多个状态申请'],[`切换${state}Tab`],`仅显示属于${state}Tab的申请`);
for(const [p,key] of [['G-guild-leave-review','006'],['G-guild-join-review','007']])nav(`${p}-${key}`,'申请卡片',`${p.includes('leave')?'退会':'入会'}申请详情`);
for(const state of ['在会','已退会'])s('G-guild-member-list-005',`公会主播${state}与搜索交集`,[`当前公会存在${state}且昵称匹配及不匹配的主播`],[`选择${state}Tab`,'输入匹配昵称'],'仅显示当前公会状态和昵称均匹配的主播');
o('G-guild-member-list-004','公会主播列表范围',['有本公会在会主播、历史退会主播、另一公会主播和普通用户'],'仅展示本公会在会及历史退会主播');
o('G-guild-member-list-003','历史退会主播标记',['目标主播已退会'],'该主播显示【退会】');
nav('G-guild-member-list-005','主播卡片','主播详情');
o('G-guild-profile-001','公会ID永久只读',[],'公会ID不可编辑');
textBoundary('G-guild-profile-003','公会名称',40,{required:true,trim:true});textBoundary('G-guild-profile-004','公会简介',200);
for(const format of ['JPG','PNG','WebP'])s('G-guild-profile-002',`公会Logo支持${format}`,['准备可读取的'+format+'图片'],[`选择${format}图片作为Logo`,'点击保存'],'当前公会Logo更新为所选图片');
s('G-guild-profile-005','保存资料不改公会关系',['已记录当前公会ID与主播关系'],['修改合法公会简介','点击保存'],'公会ID与主播关系保持不变');
for(const lang of ['简体中文','英文','印尼语','马来语'])s(['G-guild-settings-002','G-guild-settings-003'],`公会端语言${lang}`,[],[`选择${lang}`],`当前账号公会端界面使用${lang}`);
nav('G-guild-settings-004','修改密码','修改密码');
for(const yes of [true,false])s('G-guild-settings-004',`公会退出登录${yes?'确认':'取消'}`,[],['点击退出登录',`点击${yes?'确认':'取消'}`],yes?'会话清除并返回公会登录页':'仍保持当前登录会话');
for(const field of ['当前密码','新密码','确认新密码'])required(`G-guild-password-${{当前密码:'001',新密码:'002',确认新密码:'003'}[field]}`,[field],'保存');
for(const n of [7,8,9])s('G-guild-password-002',`公会新密码${n}位`,['当前密码填写正确，确认密码与新密码一致，新密码不同于旧密码'],[`输入${n}位新密码`,'点击保存'],n<8?'不能保存新密码':'密码更新并返回账号设置');
for(const [issue,expected] of [['当前密码错误','当前密码错误'],['新旧密码相同','新密码不能和旧密码一样'],['保存请求失败','保存失败']])s('G-guild-password-004',`公会改密${issue}`,[issue],['点击保存'],`保留输入并提示“${expected}”`,{type:'异常用例'});
s('G-guild-password-003','确认密码不一致',['当前密码正确，新密码符合长度'],['确认密码填写另一值','点击保存'],'密码不能更新',{type:'异常用例'});
for(const state of ['已通过','已驳回'])o('G-guild-join-review-detail-007',`已${state.slice(1)}入会申请只读`,[`申请已处理为${state}`],'不再提供重复审核操作');
textBoundary('G-guild-join-review-detail-004','驳回理由',200);
for(const material of ['本人照片','证件正面','证件反面'])nav('G-guild-join-review-detail-009',material,'对应认证材料大图');
for(const action of ['通过','驳回'])s(['G-guild-leave-review-detail-006','G-guild-leave-review-detail-007','G-guild-leave-review-detail-008'],`退会审核${action}`,['申请待审核，主播未结收益为0且正在直播'],[`点击${action}`,action==='通过'?'确认通过':'填写可选驳回理由后确认'],action==='通过'?'当前申请处理为已通过，公会关系解除':'当前申请已驳回，保留公会和主播身份',f(action==='通过'?'approveLeave':'rejectLeave'));
s('G-guild-leave-review-detail-008','退会通过取消确认',['申请待审核'],['点击通过','取消确认'],'申请仍为待审核');
textBoundary('G-guild-leave-review-detail-008','驳回理由',200);
o('G-guild-leave-review-detail-008','已处理退会只读',['当前退会申请已处理'],'不能再次通过或驳回');
for(const unclosed of [0,1])o('G-guild-host-detail-009',`移出主播未结收益${unclosed}`,['该主播当前在会',`未结收益为${unclosed}`],`移出按钮${unclosed?'置灰':'可用'}`);
s('G-guild-host-detail-009','移出主播确认',['主播在会且未结收益0，正在直播'],['点击移出公会','确认移出'],'当前直播结束且公会关系解除',f('removeHost'));
s('G-guild-host-detail-008','公会关闭主播权限',['平台未锁定公会管理，主播权限开启且正在直播'],['关闭直播权限','确认'],'主播当前直播立即结束且不能再次开播',f('guildClosePermission'));
s('G-guild-host-detail-008','取消关闭主播权限',['主播权限开启且正在直播'],['关闭直播权限','取消确认'],'权限与当前直播保持不变');
o('G-guild-host-detail-007','平台锁定公会开关只读',['平台已锁定该主播公会管理权限'],'公会直播权限开关不可编辑',f('lockPermission'));
for(const old of ['开启','关闭'])o('G-guild-host-detail-007',`解锁恢复原${old}`,['平台已解除此前锁定',`锁定前公会设置为${old}`],`公会直播权限恢复为${old}`,f('unlockPermission'));
for(const target of ['直播记录','违规记录','主播分成'])nav('G-guild-host-detail-003',target,target);
nav('G-guild-host-detail-010','业绩','主播数据');nav('G-guild-host-detail-010','认证材料','认证材料大图');

for(const condition of ['账号封禁','公会无效','认证未通过','平台权限关闭','公会权限关闭'])o('A-admin-host-list-004',`最终开播权限受${condition}限制`,[`仅${condition}，其他四个开播条件均满足`],'最终开播权限不可用');
o('A-admin-host-list-004','五项开播条件均满足',['账号可用、公会有效、认证通过、平台与公会权限均开启'],'最终开播权限可用');
s('A-admin-host-list-007','平台关闭直播权限',['目标主播正在直播且平台权限开启'],['关闭目标主播直播权限','填写原因并确认'],'目标当前场次结束，平台权限关闭',f('closePermission'));
for(const original of ['开启','关闭'])s('A-admin-host-list-008',`平台锁定保留公会原${original}`,[`公会设置原为${original}，平台权限开启`],['锁定公会管理权限','填写原因并确认'],'公会权限跟随平台且不可编辑',f('lockPermission'));
s('A-admin-host-detail-007','解封不恢复直播权限',['主播账号封禁且平台直播权限关闭'],['选择解封','填写原因并确认'],'账号解除封禁，平台直播权限仍关闭',f('unban'));
for(const action of ['变更权限','警告','封禁','解封'])s('A-admin-host-list-009',`${action}记录审计`,[`目标主播处于可执行${action}的状态`],[`选择${action}`,'填写原因并确认'],'处置记录包含前后值、当前操作人和处理时间');
s('A-admin-host-list-009','导出当前筛选主播',['当前筛选仅命中一名主播'],['点击导出','打开导出文件'],'导出只包含当前筛选命中的主播');
for(const state of ['待审核','已通过','已驳回'])s('A-admin-host-review-008',`认证审核${state}交集筛选`,['存在不同状态、主播和公会的申请'],[`设置状态${state}`,'选择目标主播和公会','查询'],'结果仅包含三项条件均匹配的申请');
o('A-admin-host-review-002','重新认证新单号',['同一账号先后提交两次认证申请'],'两次申请单号不同且历史申请保留');
required('A-admin-host-review-detail-007',['驳回原因'],'确认');
s('A-admin-host-review-detail-007','认证驳回通知申请人',['当前申请待审核'],['选择驳回','填写驳回原因','确认'],'审核结果为已驳回并向申请人发送该原因');
for(const state of ['已通过','已驳回'])o('A-admin-host-review-detail-009',`认证${state}不能再处理`,[`当前申请为${state}`],'申请结果只读，不可再次提交审核');
o('A-admin-host-review-detail-003','认证材料保留提交快照',['申请时认证资料已记录，用户随后修改个人资料'],'本申请认证材料仍为提交时快照');

for(const field of ['名称','Logo'])required('A-admin-guild-detail-003',[field],'保存');
for(const field of ['公会长','管理账号'])required('A-admin-guild-detail-004',[field],'保存');
required('A-admin-guild-detail-006',['初始密码'],'创建');
s('A-admin-guild-detail-004','公会管理账号全局重复',['另一公会已使用账号guild100'],['新建公会时填写管理账号guild100','填写其他必填资料','保存'],'不创建重复管理账号',{type:'异常用例'});
o('A-admin-guild-detail-002','已建公会ID不可修改',['公会已创建'],'公会ID只读');
for(const [guild,account] of [['启用','启用'],['停用','启用'],['启用','停用']])o('A-admin-guild-detail-010',`公会${guild}账号${account}登录条件`,[`当前公会${guild}，管理账号${account}`],`该管理账号${guild==='启用'&&account==='启用'?'满足':'不满足'}登录条件`);
s('A-admin-guild-list-007','只停用公会长账号',['公会启用，公会长账号启用，主播正常在会'],['切换公会长账号为停用','确认'],'仅公会长账号停用，公会与主播状态保持不变',f('disableLeader'));
s('A-admin-guild-list-006','停用公会保留管理账号自身状态',['公会启用，两个管理账号自身均启用'],['停用公会','确认'],'所有管理账号不可登录，但自身状态仍为启用',f('disableGuild'));
for(const amount of [0,1])s(['A-admin-guild-list-008','A-admin-guild-detail-012'],`解散公会未结收益${amount}`,['公会尚未解散',`全部主播未结收益合计${amount}`],['点击解散',...(amount===0?['确认解散']:[])],amount===0?'公会状态为已解散':'公会不能解散',f('dissolveGuild'));
o('A-admin-guild-list-005','已解散公会为终态',['公会已解散'],'不提供重新启用该公会的操作');
s('A-admin-guild-detail-012','重置密码不改管理账号',['公会管理账号已建立'],['重置管理账号密码','确认'],'管理账号保持原值，新密码立即生效');
o('A-admin-guild-detail-007','公会详情主播隔离',['两个公会各有不同主播'],'当前详情只显示当前公会主播');
for(const value of ['',0,-1,1,1.5])s('A-admin-guild-recommendation-detail-003',`推荐权重${value===''?'空值':value}`,['已选择有效且未配置公会'],[value===''?'清空权重':`输入权重${value}`,'保存'],value!==''&&Number.isInteger(value)&&value>0?'推荐保存成功':'推荐不能保存',{type:'逻辑校验'});
for(const condition of ['已配置','无效'])s('A-admin-guild-recommendation-detail-002',`推荐公会${condition}`,['目标公会'+condition],['新增推荐','选择目标公会','保存'],'目标公会不能重复或无效配置',{type:'异常用例'});
o('A-admin-guild-recommendation-003','推荐高权重优先',['两公会权重分别1和2'],'权重2公会在前');
o('A-admin-guild-recommendation-detail-003','推荐同权重最近更新优先',['两公会权重相同，更新时间不同'],'最近更新公会在前');
s(['A-admin-guild-recommendation-005','A-admin-guild-recommendation-006'],'移除推荐不改公会',['目标启用公会已被推荐'],['移除该推荐','确认'],'公会不再推荐，自身仍为启用');
