import {scenario as s,observe as o,navigation as nav} from './design.mjs';

for(const [id,label] of [
 ['U-live-data-003','用户日有效天'],['U-views_live-data_month-004','用户月有效天'],['U-host-center-009','主播中心有效天'],['G-guild-host-list-003','公会主播有效天'],['G-guild-income-day-detail-004','公会当日有效天人数'],['A-admin-dashboard-006','工作台有效天人数'],['A-admin-daily-statistics-008','每日统计有效天人数'],['A-admin-host-statistics-006','主播统计有效天人数'],['A-admin-monthly-host-share-004','主播业绩达标天数']])for(const seconds of [10799,10800,10801,21600])o(id,`${label}${seconds}秒`,['当前范围仅一名主播、同一个已确定自然日',`该日累计有效直播时长${seconds}秒`],`${label} = ${seconds>=10800?1:0}`,{type:'逻辑校验'});
o('A-admin-host-live-record-report-005','达标累计多场不按单场',['同一主播同一自然日已完成两场各90分钟直播'],'该自然日累计180分钟，两条场次记录的是否达标均为是');
for(const [id,label] of [['U-live-data-002','主播直播数据收益'],['U-views_live-data_month-003','用户月收益'],['U-live-records-007','用户场次收益汇总'],['U-live-end-host-003','本场收益'],['U-host-center-003','本月收益'],['G-guild-home-004','公会今日礼物收益'],['G-guild-live-gift-detail-005','公会场次礼物收益'],['A-admin-host-list-005','后台主播金币收益'],['A-admin-live-management-008','后台场次主播收益'],['A-admin-monthly-host-share-008','主播业绩总收益'],['A-admin-monthly-income-expense-003','月度主播收益']]){
 const giftOnly=id.startsWith('G-');
 o(id,`${label}区分幸运赠礼`,['范围内普通礼物100、定制礼物200、幸运礼物1000且赠送时比例1%，返奖900',...(giftOnly?[]:['另有门票50'])],`${label} = 100 + 200 + 1000 × 1%${giftOnly?'':' + 50'} = ${giftOnly?310:360}金币`,{type:'逻辑校验'});
 o(id,`${label}排除虚拟和失败`,['范围内真实成功普通礼物100，另有虚拟礼物100、失败礼物50'],`${label} = 100金币`,{type:'逻辑校验'});
}
for(const [id,label] of [['A-admin-user-list-006','累计消费'],['A-admin-live-management-005','场次消费金币'],['A-admin-live-detail-004','直播详情金币收益字段'],['A-admin-recharge-statistics-007','充值消费汇总消费金币'],['A-admin-monthly-viewer-consumption-005','用户累计消费'],['A-admin-host-live-record-report-007','场次报表消费金币']])o(id,`${label}使用用户净消耗`,['普通100、定制200、门票50、幸运投入1000返奖900，另有虚拟礼物300'],`${label} = 100 + 200 + 50 + 1000 - 900 = 450金币`,{type:'逻辑校验'});
for(const id of ['A-admin-consumption-order-detail-003','A-admin-consumption-order-detail-report-004','A-admin-operation-gift-records-004','A-admin-operation-account-detail-005','U-views_live-room_contribution-gifts-003'])o(id,'单价与数量乘积',['本笔记录单价10、数量3'],'金额 = 10 × 3 = 30金币',{type:'逻辑校验'});
for(const id of ['A-admin-monthly-host-earnings-005','A-admin-monthly-host-share-007'])o(id,'幸运礼物按赠送比例快照',['第一笔价值1000比例1%，第二笔价值1000比例2%，之后全局比例修改为3%'],'收益 = 1000 × 1% + 1000 × 2% = 30金币',{type:'逻辑校验'});
o('A-admin-monthly-gift-sales-005','礼物销售额不减返奖',['成功真实金币幸运礼物单价10数量100，返奖900'],'销售额 = 10 × 100 = 1000金币',{type:'逻辑校验'});
o('A-admin-monthly-host-earnings-004','普通定制收益单价乘份数',['普通礼物单价10成功份数3'],'收益 = 10 × 3 = 30金币',{type:'逻辑校验'});
for(const id of ['A-admin-daily-statistics-009','A-admin-host-statistics-007'])for(const [durations,expected] of [[[10,30,20],20],[[10,20,30,40],25]])o(id,`直播时长${durations.length}项中位数`,[`当前有效场次时长为${durations.join('、')}分钟`],`开播时长中位数 = ${expected}分钟`,{type:'逻辑校验'});
o('A-admin-daily-statistics-009','无场次时长中位数0',['统计日没有有效场次'],'开播时长中位数为0');
for(const [id,label] of [['A-admin-dashboard-005','新用户ARPU'],['A-admin-data-overview-006','新用户ARPU'],['A-admin-daily-statistics-006','新用户ARPU'],['A-admin-user-activity-statistics-006','新用户ARPU'],['A-admin-user-activity-statistics-007','老用户ARPU'],['A-admin-recharge-statistics-004','客单价']])for(const n of [0,2])o(id,`${label}分母${n}`,[`对应充值用户数${n}，对应支付成功金额${n?30:0}USD`],`${label} = ${n?'30 ÷ 2 = 15':'0'}USD`,{type:'逻辑校验'});
for(const [seconds,expected] of [[29,0],[30,1],[31,1],[89,1],[90,2]])o('A-admin-live-statistics-004',`观看时长${seconds}秒取整`,[`当天有效观看秒数合计${seconds}`],`观看时长 = ${expected}分钟`,{type:'逻辑校验'});
for(const n of [0,2])o('A-admin-live-statistics-005',`人均观看分母${n}`,[`当天观众${n}人，有效观看${n?180:0}秒`],`人均观看时长 = ${n?2:0}分钟`,{type:'逻辑校验'});
for(const n of [0,3])o('A-admin-live-statistics-006',`访问率分母${n}`,[`成功进入观众${n?1:0}人，访问次数${n}`],`访问率 = ${n?'33.3':'0'}%`,{type:'逻辑校验'});
for(const n of [0,4])o('A-admin-host-statistics-005',`开播率分母${n}`,[`当日有效主播${n}，成功开播${n?1:0}`],`开播率 = ${n?'25':'0'}%`,{type:'逻辑校验'});
for(const [id,label] of [['A-admin-dashboard-002','活跃用户'],['A-admin-daily-statistics-003','活跃用户']])o(id,`${label}打开事件去重`,['同日登录用户甲启动2次且后台切前台1次，用户乙启动1次，游客启动3次'],'活跃用户数为2');
o('A-admin-user-active-statistics-003','登录用户按登录去重',['同日甲成功登录3次、乙1次、丙登录失败'],'登录用户为2');
o('A-admin-user-active-statistics-005','新老用户互斥汇总',['当日登录用户中2人当日注册、3人在统计日前注册'],'新用户2、老用户3，登录用户 = 2 + 3 = 5');
o('A-admin-user-active-statistics-007','每日求和不跨日去重',['同一用户连续两天各登录一次，范围仅这两日'],'汇总登录用户为2');
o('A-admin-data-overview-003','概览活跃按日求和',['同一登录用户在所选两日均打开App，其他用户无活动'],'活跃汇总为2');
o('A-admin-data-overview-004','概览充值人数按日求和',['同一用户所选两日各成功充值一次'],'充值人数汇总为2');
for(const id of ['A-admin-dashboard-003','A-admin-daily-statistics-004','A-admin-recharge-statistics-003'])o(id,'充值金额人数订单区分',['当日甲成功支付10USD与20USD，乙成功支付30USD，丙40USD支付失败'],'成功金额60USD、去重充值人数2；有订单指标时为3笔');
for(const id of ['A-admin-dashboard-004','A-admin-data-overview-005','A-admin-daily-statistics-005'])o(id,'新用户充值只计注册当日',['当日新注册用户甲充值10USD，昨日注册乙今日充值20USD'],'新用户充值金额10USD');
for(const id of ['A-admin-daily-statistics-007','A-admin-host-statistics-004'])o(id,'多场开播主播去重',['主播甲当日开播2场、乙开播1场'],'开播人数2，有场次指标时场次为3');
o('A-admin-host-statistics-008','连麦场次按场次去重',['同一场直播发生两次有效连麦，另一场无连麦'],'连麦场次数为1');
o('A-admin-host-statistics-009','确认违规去重主播及场次',['同主播在同场有两条确认违规，另一场有一条确认违规，另有一条误报'],'违规主播1，违规场次2');
for(const id of ['A-admin-live-management-004','A-admin-live-detail-003','G-guild-host-data-005','G-guild-live-gift-detail-004'])o(id,'同用户重复进场观众去重',['同一场次用户甲进入2次，乙进入1次'],'该场观众人数为2');
for(const id of ['A-admin-live-management-007','A-admin-live-detail-005','G-guild-host-data-006'])o(id,'礼物件数连送累计',['成功赠礼数量2和3，另有一张门票和失败赠礼4件'],'收礼数量 = 2 + 3 = 5');
o('G-guild-live-gift-detail-004','送礼观众按用户去重',['甲送礼2笔，乙送礼1笔，丙仅观看'],'送礼观众2人');
o('U-live-data-005','用户观众人次重复进入累计',['同一场用户甲进入2次，乙进入1次'],'观众人次为3');
for(const live of [true,false])o('A-admin-live-management-006',`场次时长${live?'直播中':'已结束'}`,[`开播10:00，${live?'当前':'结束'}时间10:30`],'场次时长30分钟');
o('A-admin-host-live-record-report-004','场次起止时长',['开播10:00，结束11:30'],'时长90分钟');
o('A-admin-monthly-host-share-003','统计天数包含首尾',['筛选开始9月1日、结束9月3日'],'统计天数 = 3 - 1 + 1 = 3天',{type:'逻辑校验'});
o('A-admin-monthly-host-share-003','同日统计1天',['开始和结束均为9月1日'],'统计天数为1');
o('A-admin-recharge-statistics-005','充值金币不混赠币',['成功充值两笔基础100和200、赠送20和30'],'充值金币 = 100 + 200 = 300');
o('A-admin-recharge-statistics-006','套餐与系统赠币分别统计',['套餐赠币20，签到10，任务30'],'充值赠送20，系统赠送40');
o('A-admin-recharge-statistics-009','退款扣回不算消费',['退款扣回120，成功普通礼物消费10'],'退款资产扣回120单列，消费金币10');
o('A-admin-user-activity-statistics-003','新老充值金额汇总',['新用户成功充值10，老用户成功充值20'],'总充值金额30');
o('A-admin-user-activity-statistics-004','新老充值人数汇总',['新充值用户2，老充值用户3'],'总充值人数5');
o('A-admin-daily-statistics-010','退款按完成日统计',['两笔充值分别前月发生，今日退款完成10和20USD'],'今日退款订单2，退款金额30USD');
o('A-admin-monthly-income-expense-005','月度退款不按原支付月',['8月支付10USD，9月全额退款完成'],'10USD退款计入9月');
o('A-admin-recharge-order-detail-report-006','充值明细排除失败',['范围内一笔支付成功、一笔失败'],'充值报表仅包含成功订单');
o('A-admin-refund-order-detail-report-005','退款明细仅充值退款',['存在完成的充值退款，以及原成功礼物与门票消费'],'退款报表仅包含充值退款记录');
for(const id of ['A-admin-monthly-host-earnings-006','A-admin-monthly-gift-sales-006','A-admin-consumption-order-detail-report-007','A-admin-monthly-viewer-consumption-006'])o(id,'报表排除运营虚拟赠礼',['当前范围有一筆真实金币赠礼和一笔虚拟金币赠礼'],'本报表只纳入成功真实金币赠礼');

o('U-views_live-data_month-002','月数据默认当前自然月',[],'默认选择当前自然月');
s('U-views_live-data_month-010','切换无数据月份清零',['原月份各项数据非0，目标月份无数据'],['选择目标无数据月份'],'全部指标为0，不残留原月数据');
for(const preset of ['本周','本月','上月','单日','连续日期范围'])s('U-live-records-013',`用户直播记录${preset}`,['当前主播在范围内外均有已开始场次'],[`选择${preset}`],'仅显示对应范围的当前主播场次');
o('U-live-records-011','直播记录默认近7天',[],'默认筛选近7天');
o('U-live-records-012','直播记录按开播倒序',['两场直播开播时间不同'],'后开播场次在前');
o('U-live-records-006','当前设置不改历史场次',['历史场次主题甲、分类唱歌，当前设置改为乙、聊天'],'历史记录仍为主题甲、分类唱歌');
o('U-live-records-008','用户场次总时长汇总',['筛选内两场分别30和60分钟'],'总时长90分钟，场次2');
o('U-live-records-003','进行中结束时间为空',['目标场次仍在直播'],'结束时间为空');
s('U-live-data-009','数据进入记录保留日期',['直播数据已选本月'],['进入直播记录'],'记录页沿用本月日期范围');
nav('U-live-records-015','一条场次','该场次数据与礼物明细');
o('U-income-sharing-006','分成金额印尼格式',['该笔已上传最终分成1234.56USD'],'金额以美元展示为1.234,56');
o('U-income-sharing-004','主播分成没有线上申请审批',[],'只显示已上传结果，不提供线上结算申请或审批');
o('U-income-sharing-007','主播分成日期倒序',['当前主播有两条不同日期分成，另一主播有一条'],'仅当前主播结果按分成日期倒序');
nav('U-income-sharing-009','返回','主播中心');
o('G-guild-host-list-004','退会保留发生时公会业绩',['主播在甲公会直播后已退会加入乙'],'原甲公会直播业绩保留并标【退会】，不转入乙历史');
o('G-guild-host-list-002','主播达标人数按中位数',['全部已完成开播主播有效天为1、2、3、4'],'有效天中位数2.5，达标人数2');
for(const p of ['G-guild-host-list','G-guild-host-data','G-guild-income'])o(`${p}-002`,'开播人数以完成场次去重',['甲完成两场、乙完成一场、丙仅有进行中场次'],'开播人数为2');
o('G-guild-income-day-detail-003','公会当日已开播收益倒序',['已开播主播收益10和20'],'收益20主播在前');
o('G-guild-home-003','公会首页当前直播中人数',['当前公会甲正在直播、乙已结束，另一公会丙正在直播'],'直播中人数1');
o('G-guild-income-day-detail-004','历史日直播中字段使用当日开播数',['当前查看历史日期，该日2名主播开播，当前均不在播'],'历史日该指标显示2');
for(const mode of ['日','月'])s('G-guild-host-summary-006',`公会主播${mode}数据下钻`,[`当前选择主播甲的某${mode}`],[`点击该${mode}数据行`],`进入直播记录并带入主播甲及对应${mode}范围`);
s('G-guild-host-data-008','公会场次下钻保留标识',['当前列表有主播甲场次1001'],['点击场次1001'],'详情带入主播甲、日期和场次1001');
s('G-guild-live-gift-detail-007','公会场次返回保留筛选',['从选定主播和日期的记录列表进入详情'],['点击返回'],'原主播与日期筛选保留');
for(const mode of ['日','月'])s('G-guild-income-007',`公会业绩${mode}下钻`,[],[`点击${mode}数据行`],`进入主播业绩并带入该${mode}范围`);
o('A-admin-dashboard-008','工作台最新日与近7日',['已记录最新可用自然日为9月10日'],'指标使用9月10日，趋势使用9月4日至10日');
s('A-admin-data-overview-009','报表结束早于开始',['开始9月2日，结束9月1日'],['点击查询'],'不能按反向日期范围查询');
o('A-admin-report-center-004','报表入口按角色授权',['当前账号仅获用户活跃报表查询权限，无其他报表权限'],'只显示获授权报表入口');
